table mart_renewal_risk
	lineageTag: c6fac121-9e44-53c6-a312-41423f0f4bf9

	column subscription_id
		dataType: string
		lineageTag: f247fc0e-f177-510d-b62f-23c1aca5a4fc
		summarizeBy: none
		sourceColumn: subscription_id

	column customer_id
		dataType: string
		lineageTag: 640aae38-59dd-5d8d-a2d1-9b13232d1b62
		summarizeBy: none
		sourceColumn: customer_id

	column plan_id
		dataType: string
		lineageTag: 04c6d45c-9982-5e1b-9374-cea8c4214a9c
		summarizeBy: none
		sourceColumn: plan_id

	column due_date
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 5b14f6e5-6bec-55dc-941f-a16f3b5a51de
		summarizeBy: none
		sourceColumn: due_date

	column failed_attempts
		dataType: int64
		formatString: #,0
		lineageTag: 3ecf2e25-712b-5c3b-8f75-7e86b000e3fc
		summarizeBy: sum
		sourceColumn: failed_attempts

	column risk_level
		dataType: string
		lineageTag: 2e56fe7e-b05e-569d-af8c-3a753ed4f67a
		summarizeBy: none
		sourceColumn: risk_level
		sortByColumn: risk_order

	column risk_order
		dataType: int64
		formatString: 0
		lineageTag: bb7fc45a-fb89-5197-9264-6706d08a8b43
		summarizeBy: none
		sourceColumn: risk_order

	partition mart_renewal_risk = m
		mode: import
		source =
				let
				    Source = #table(type table [#"subscription_id" = nullable text, #"customer_id" = nullable text, #"plan_id" = nullable text, #"due_date" = nullable text, #"failed_attempts" = nullable text, #"risk_level" = nullable text, #"risk_order" = nullable text], {
				        {"sub-000170", "c-001776", "founder_community", "2026-09-23", "1", "high", "1"},
				        {"sub-000179", "c-001888", "founder_community", "2026-09-29", "0", "medium", "2"},
				        {"sub-000202", "c-002142", "founder_community", "2026-10-05", "0", "medium", "2"},
				        {"sub-000221", "c-002398", "founder_community", "2026-10-10", "0", "not_due", "3"},
				        {"sub-000190", "c-002016", "founder_community", "2026-10-13", "0", "not_due", "3"},
				        {"sub-000224", "c-002426", "founder_community", "2026-10-13", "0", "not_due", "3"},
				        {"sub-000273", "c-003004", "founder_community", "2026-10-26", "0", "not_due", "3"},
				        {"sub-000292", "c-003135", "founder_community", "2026-10-28", "0", "not_due", "3"},
				        {"sub-000303", "c-003195", "founder_community", "2026-10-29", "0", "not_due", "3"},
				        {"sub-000259", "c-002819", "founder_community", "2026-10-31", "0", "not_due", "3"},
				        {"sub-000314", "c-003371", "founder_community", "2026-11-08", "0", "not_due", "3"},
				        {"sub-000327", "c-003466", "founder_community", "2026-11-13", "0", "not_due", "3"},
				        {"sub-000294", "c-003150", "founder_community", "2026-11-14", "0", "not_due", "3"},
				        {"sub-000334", "c-003553", "founder_community", "2026-11-14", "0", "not_due", "3"},
				        {"sub-000338", "c-003566", "founder_community", "2026-11-14", "0", "not_due", "3"},
				        {"sub-000284", "c-003090", "founder_community", "2026-11-15", "0", "not_due", "3"},
				        {"sub-000319", "c-003399", "founder_community", "2026-11-22", "0", "not_due", "3"},
				        {"sub-000359", "c-003779", "founder_community", "2026-11-25", "0", "not_due", "3"},
				        {"sub-000345", "c-003642", "founder_community", "2026-11-29", "0", "not_due", "3"},
				        {"sub-000354", "c-003726", "founder_community", "2026-11-29", "0", "not_due", "3"},
				        {"sub-000382", "c-004010", "founder_community", "2026-12-13", "0", "not_due", "3"},
				        {"sub-000388", "c-004118", "founder_community", "2026-12-14", "0", "not_due", "3"},
				        {"sub-000406", "c-004334", "founder_community", "2026-12-17", "0", "not_due", "3"},
				        {"sub-000414", "c-004417", "founder_community", "2026-12-17", "0", "not_due", "3"},
				        {"sub-000412", "c-004405", "founder_community", "2026-12-22", "0", "not_due", "3"},
				        {"sub-000417", "c-004461", "founder_community", "2026-12-25", "0", "not_due", "3"},
				        {"sub-000362", "c-003788", "founder_community", "2026-12-29", "0", "not_due", "3"},
				        {"sub-000435", "c-004624", "founder_community", "2027-01-03", "0", "not_due", "3"},
				        {"sub-000455", "c-004800", "founder_community", "2027-01-03", "0", "not_due", "3"},
				        {"sub-000486", "c-005006", "founder_community", "2027-01-04", "0", "not_due", "3"},
				        {"sub-000504", "c-005187", "founder_community", "2027-01-15", "0", "not_due", "3"},
				        {"sub-000519", "c-005330", "founder_community", "2027-01-17", "0", "not_due", "3"},
				        {"sub-000480", "c-004969", "founder_community", "2027-01-18", "0", "not_due", "3"},
				        {"sub-000535", "c-005471", "founder_community", "2027-01-29", "0", "not_due", "3"},
				        {"sub-000514", "c-005302", "founder_community", "2027-02-03", "0", "not_due", "3"},
				        {"sub-000529", "c-005412", "founder_community", "2027-02-03", "0", "not_due", "3"},
				        {"sub-000540", "c-005550", "founder_community", "2027-02-04", "0", "not_due", "3"},
				        {"sub-000576", "c-005962", "founder_community", "2027-02-04", "0", "not_due", "3"},
				        {"sub-000565", "c-005774", "founder_community", "2027-02-07", "0", "not_due", "3"},
				        {"sub-000548", "c-005615", "founder_community", "2027-02-08", "0", "not_due", "3"},
				        {"sub-000578", "c-005967", "founder_community", "2027-02-09", "0", "not_due", "3"},
				        {"sub-000599", "c-006252", "founder_community", "2027-02-19", "0", "not_due", "3"},
				        {"sub-000591", "c-006188", "founder_community", "2027-02-20", "0", "not_due", "3"},
				        {"sub-000640", "c-006659", "founder_community", "2027-03-03", "0", "not_due", "3"},
				        {"sub-000657", "c-006768", "founder_community", "2027-03-07", "0", "not_due", "3"},
				        {"sub-000659", "c-006771", "founder_community", "2027-03-09", "0", "not_due", "3"},
				        {"sub-000635", "c-006651", "founder_community", "2027-03-12", "0", "not_due", "3"},
				        {"sub-000703", "c-007162", "founder_community", "2027-03-15", "0", "not_due", "3"},
				        {"sub-000676", "c-006993", "founder_community", "2027-03-17", "0", "not_due", "3"},
				        {"sub-000691", "c-007072", "founder_community", "2027-03-18", "0", "not_due", "3"},
				        {"sub-000683", "c-007014", "founder_community", "2027-03-25", "0", "not_due", "3"},
				        {"sub-000730", "c-007399", "founder_community", "2027-03-30", "0", "not_due", "3"},
				        {"sub-000711", "c-007202", "founder_community", "2027-04-02", "0", "not_due", "3"},
				        {"sub-000716", "c-007263", "founder_community", "2027-04-02", "0", "not_due", "3"},
				        {"sub-000681", "c-007013", "founder_community", "2027-04-04", "0", "not_due", "3"},
				        {"sub-000743", "c-007526", "founder_community", "2027-04-08", "0", "not_due", "3"},
				        {"sub-000751", "c-007614", "founder_community", "2027-04-08", "0", "not_due", "3"},
				        {"sub-000754", "c-007650", "founder_community", "2027-04-13", "0", "not_due", "3"},
				        {"sub-000784", "c-007937", "founder_community", "2027-04-13", "0", "not_due", "3"},
				        {"sub-000736", "c-007488", "founder_community", "2027-04-14", "0", "not_due", "3"},
				        {"sub-000738", "c-007499", "founder_community", "2027-04-15", "0", "not_due", "3"},
				        {"sub-000798", "c-008049", "founder_community", "2027-04-24", "0", "not_due", "3"},
				        {"sub-000795", "c-008040", "founder_community", "2027-04-25", "0", "not_due", "3"},
				        {"sub-000808", "c-008154", "founder_community", "2027-04-28", "0", "not_due", "3"},
				        {"sub-000792", "c-008034", "founder_community", "2027-04-29", "0", "not_due", "3"},
				        {"sub-000877", "c-008682", "founder_community", "2027-05-03", "0", "not_due", "3"},
				        {"sub-000840", "c-008501", "founder_community", "2027-05-07", "0", "not_due", "3"},
				        {"sub-000857", "c-008588", "founder_community", "2027-05-09", "0", "not_due", "3"},
				        {"sub-000843", "c-008506", "founder_community", "2027-05-11", "0", "not_due", "3"},
				        {"sub-000826", "c-008365", "founder_community", "2027-05-12", "0", "not_due", "3"},
				        {"sub-000879", "c-008683", "founder_community", "2027-05-14", "0", "not_due", "3"},
				        {"sub-000869", "c-008645", "founder_community", "2027-05-15", "0", "not_due", "3"},
				        {"sub-000873", "c-008668", "founder_community", "2027-05-15", "0", "not_due", "3"},
				        {"sub-000850", "c-008548", "founder_community", "2027-05-20", "0", "not_due", "3"},
				        {"sub-000861", "c-008597", "founder_community", "2027-05-20", "0", "not_due", "3"},
				        {"sub-000881", "c-008694", "founder_community", "2027-05-20", "0", "not_due", "3"},
				        {"sub-000883", "c-008730", "founder_community", "2027-05-21", "0", "not_due", "3"},
				        {"sub-000904", "c-008914", "founder_community", "2027-05-23", "0", "not_due", "3"},
				        {"sub-000923", "c-009052", "founder_community", "2027-05-26", "0", "not_due", "3"},
				        {"sub-000928", "c-009098", "founder_community", "2027-05-26", "0", "not_due", "3"},
				        {"sub-000947", "c-009272", "founder_community", "2027-05-27", "0", "not_due", "3"},
				        {"sub-000911", "c-008959", "founder_community", "2027-05-29", "0", "not_due", "3"},
				        {"sub-000916", "c-008986", "founder_community", "2027-06-05", "0", "not_due", "3"},
				        {"sub-000942", "c-009256", "founder_community", "2027-06-05", "0", "not_due", "3"},
				        {"sub-000949", "c-009290", "founder_community", "2027-06-07", "0", "not_due", "3"},
				        {"sub-000996", "c-009712", "founder_community", "2027-06-12", "0", "not_due", "3"},
				        {"sub-000952", "c-009294", "founder_community", "2027-06-15", "0", "not_due", "3"},
				        {"sub-000969", "c-009477", "founder_community", "2027-06-16", "0", "not_due", "3"},
				        {"sub-001000", "c-009753", "founder_community", "2027-06-16", "0", "not_due", "3"},
				        {"sub-000965", "c-009461", "founder_community", "2027-06-20", "0", "not_due", "3"},
				        {"sub-000972", "c-009493", "founder_community", "2027-06-23", "0", "not_due", "3"},
				        {"sub-001029", "c-010223", "founder_community", "2027-07-04", "0", "not_due", "3"},
				        {"sub-001067", "c-010713", "founder_community", "2027-07-05", "0", "not_due", "3"},
				        {"sub-001023", "c-010137", "founder_community", "2027-07-08", "0", "not_due", "3"},
				        {"sub-001049", "c-010490", "founder_community", "2027-07-08", "0", "not_due", "3"},
				        {"sub-001032", "c-010228", "founder_community", "2027-07-14", "0", "not_due", "3"},
				        {"sub-001060", "c-010610", "founder_community", "2027-07-14", "0", "not_due", "3"},
				        {"sub-001084", "c-010879", "founder_community", "2027-07-17", "0", "not_due", "3"},
				        {"sub-000002", "c-000002", "founder_community", "2027-07-21", "0", "not_due", "3"},
				        {"sub-001079", "c-010816", "founder_community", "2027-07-21", "0", "not_due", "3"},
				        {"sub-001070", "c-010739", "founder_community", "2027-07-23", "0", "not_due", "3"},
				        {"sub-001093", "c-010976", "founder_community", "2027-07-25", "0", "not_due", "3"},
				        {"sub-001090", "c-010934", "founder_community", "2027-07-26", "0", "not_due", "3"},
				        {"sub-000033", "c-000335", "founder_community", "2027-07-27", "0", "not_due", "3"},
				        {"sub-000010", "c-000084", "founder_community", "2027-07-29", "0", "not_due", "3"},
				        {"sub-001088", "c-010927", "founder_community", "2027-07-29", "0", "not_due", "3"},
				        {"sub-000035", "c-000344", "founder_community", "2027-08-02", "0", "not_due", "3"},
				        {"sub-001116", "c-011190", "founder_community", "2027-08-03", "0", "not_due", "3"},
				        {"sub-001125", "c-011284", "founder_community", "2027-08-06", "0", "not_due", "3"},
				        {"sub-001131", "c-011322", "founder_community", "2027-08-06", "0", "not_due", "3"},
				        {"sub-001128", "c-011301", "founder_community", "2027-08-08", "0", "not_due", "3"},
				        {"sub-001095", "c-011002", "founder_community", "2027-08-13", "0", "not_due", "3"},
				        {"sub-001142", "c-011444", "founder_community", "2027-08-14", "0", "not_due", "3"},
				        {"sub-001175", "c-011701", "founder_community", "2027-08-15", "0", "not_due", "3"},
				        {"sub-000071", "c-000830", "founder_community", "2027-08-18", "0", "not_due", "3"},
				        {"sub-000083", "c-001010", "founder_community", "2027-08-19", "0", "not_due", "3"},
				        {"sub-001136", "c-011398", "founder_community", "2027-08-19", "0", "not_due", "3"},
				        {"sub-001208", "c-012020", "founder_community", "2027-08-25", "0", "not_due", "3"},
				        {"sub-000110", "c-001216", "founder_community", "2027-08-26", "0", "not_due", "3"},
				        {"sub-000073", "c-000839", "founder_community", "2027-08-27", "0", "not_due", "3"},
				        {"sub-001167", "c-011648", "founder_community", "2027-08-29", "0", "not_due", "3"},
				        {"sub-001202", "c-011978", "founder_community", "2027-08-30", "0", "not_due", "3"},
				        {"sub-000068", "c-000789", "founder_community", "2027-09-02", "0", "not_due", "3"},
				        {"sub-000085", "c-001023", "founder_community", "2027-09-05", "0", "not_due", "3"},
				        {"sub-001219", "c-012174", "founder_community", "2027-09-06", "0", "not_due", "3"},
				        {"sub-001226", "c-012233", "founder_community", "2027-09-06", "0", "not_due", "3"},
				        {"sub-001234", "c-012321", "founder_community", "2027-09-07", "0", "not_due", "3"},
				        {"sub-001229", "c-012239", "founder_community", "2027-09-08", "0", "not_due", "3"},
				        {"sub-000133", "c-001473", "founder_community", "2027-09-10", "0", "not_due", "3"},
				        {"sub-001260", "c-012753", "founder_community", "2027-09-12", "0", "not_due", "3"},
				        {"sub-000102", "c-001124", "founder_community", "2027-09-13", "0", "not_due", "3"},
				        {"sub-000164", "c-001749", "founder_community", "2027-09-15", "0", "not_due", "3"},
				        {"sub-001286", "c-013135", "founder_community", "2027-09-15", "0", "not_due", "3"},
				        {"sub-000158", "c-001738", "founder_community", "2027-09-16", "0", "not_due", "3"},
				        {"sub-001302", "c-013384", "founder_community", "2027-09-17", "0", "not_due", "3"},
				        {"sub-000160", "c-001739", "founder_community", "2027-09-19", "0", "not_due", "3"},
				        {"sub-001324", "c-013660", "founder_community", "2027-09-19", "0", "not_due", "3"},
				        {"sub-000122", "c-001387", "founder_community", "2027-09-21", "0", "not_due", "3"},
				        {"sub-000146", "c-001607", "founder_community", "2027-09-21", "0", "not_due", "3"},
				        {"sub-001273", "c-012866", "founder_community", "2027-09-22", "0", "not_due", "3"},
				        {"sub-001306", "c-013401", "founder_community", "2027-09-22", "0", "not_due", "3"},
				        {"sub-001298", "c-013274", "founder_community", "2027-09-23", "0", "not_due", "3"},
				        {"sub-000154", "c-001698", "founder_community", "2027-09-24", "0", "not_due", "3"},
				        {"sub-000198", "c-002110", "founder_community", "2027-09-24", "0", "not_due", "3"}
				    }),
				    Typed = Table.TransformColumnTypes(Source, {{"subscription_id", type text}, {"customer_id", type text}, {"plan_id", type text}, {"due_date", type date}, {"failed_attempts", Int64.Type}, {"risk_level", type text}, {"risk_order", Int64.Type}})
				in
				    Typed
