table mart_renewal_risk
	lineageTag: 9d6f47d8-1c3d-4ba3-9259-fbd4d0508ade

	measure 'High Risk Renewals' = CALCULATE(COUNTROWS('mart_renewal_risk'), 'mart_renewal_risk'[risk_level] = "high")
		formatString: #,0
		displayFolder: Lifecycle
		lineageTag: ff746811-a5b6-4ed6-9d99-37fabc5f4a02

	measure 'Due Soon Renewals' = CALCULATE(COUNTROWS('mart_renewal_risk'), 'mart_renewal_risk'[risk_level] = "medium")
		formatString: #,0
		displayFolder: Lifecycle
		lineageTag: 9815253f-f91f-44e4-aa1e-10c6ddd2119c

	column subscription_id
		dataType: string
		lineageTag: b9c5a1ba-76ae-4ef1-a5ac-5f7d1130b27f
		summarizeBy: none
		sourceColumn: subscription_id

	column customer_id
		dataType: string
		lineageTag: eda98508-a32e-43db-8150-e744bf755a52
		summarizeBy: none
		sourceColumn: customer_id

	column plan_id
		dataType: string
		lineageTag: e4a3913a-2514-4ed4-bcf4-f58c5d245a4a
		summarizeBy: none
		sourceColumn: plan_id

	column due_date
		dataType: dateTime
		lineageTag: 812a3b51-597f-4642-a7a7-e10ebafa91cf
		summarizeBy: none
		sourceColumn: due_date

	column failed_attempts
		dataType: int64
		lineageTag: 96b7d77e-363b-4d42-83ee-50c746a9b4d8
		summarizeBy: none
		sourceColumn: failed_attempts

	column risk_level
		dataType: string
		lineageTag: 5ba5d8a6-377e-464c-8de2-b096d0c006a5
		summarizeBy: none
		sourceColumn: risk_level

	partition mart_renewal_risk = m
		mode: import
		source =
				let
				  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("pZrLjhZHDIXfhTUj2a4qX54FIaQACSwAKWEWefvUXMo/kTLnKNMLpGY0+saXY5dd3e/evfnr/rc7EdGQN2/ffLx7eArfj7//uP/+6fOfHz7++Pbt/vvXn3/vn5mY30nd2dj/0f3vy9c/vrx5//YXSh1KZjLKw+8+/NVvnz99vf/2K2f/yjPHdBriqNzJepljejijknBUnjnff/z88On+878cqxMeE3UGGi+DzOYBTbsEivEMGiKTgB7/0kugOrEeOhYD5cugIW2RFgUVsGgdFVlqEdBQYJGeYI8RCkF6J8g1iwOa7gQEs1ZtkS5hoAksGg1aa1wCZYO4awBk2RZJUdcWylp11qoIyAyAWkcjgoKQRXMdkJN2pFDZY3WMwvwKKE/RTlEcbIOCHHnSP1WTgUD6p/gBPWkTggKAumjnfPy914M6RlMWASEdPZnxBHJlIKQj71YbyYKN0j/HEeR0A8GOO9mNDaR/rgalyBVQnvQvEWcgoKMlJ/1LMwgItZHVbWSNwVyDOspz9s/yYiBwiqzO2proOHoEofSvLpE1xCDIYNaWdYyequXVoHlitNYSBkLpj9ZRuV0BeQc7YjJQINdOh1yui4FQ+iNvrgUDofTXyZrbYjFSCDrjsSvqR48gA+Oxd/rdFy6RAXXk67RaD08GCgTqGAWptQGD7V202zUGUnCKRI/HoUTZAzY27xLxqsFAKEad/pCgFgFle7ZropOA0AEZ4+go4Oj3CBpAkKHtmpEOOe8EZU29QT4ugDxvwVYKAo0tZgd7mTMQyFqstshJ1hhoNog0/wmH0egVImrEFdDorE3S2CacaqO3o5hEkBMWbdQB5R4jCMiQRbVuIBZsVGspbZEuln6090dfIKQMCgKtNuM0//TERbvgKZJ9HOUSZSDQIbOPo1xERwueItlFuy1yAlJwpZF2lJ3DFwMZCnbdgj0YCAgy/Qaa1CIkyL7RSve8Alq39E8GQmNNujao4gqom/+O1rwE6hgFWWo2COioes3KUmoRqLWyY1HJYkWL7iHLskGVV0DzFG1ZUItA9VcPEVlkql2wsVUPEVmJq99v19n/6Zq1a+saqBpUwkAoRnVcqyAbpMN+VOvmGikRh9Vf3Y+2EIKBXtaRiki7tsbrQdui1Ra5EhCq/oqO0SxmEShalbP37yfDoEDDqIrHAYVS0EIWjQNSMvoFGkZVZrs2ibIJaNgtRklACmMkB+QqV0BnPNbn0xuCQNFKv157fkQgcIrspHewU/0SqGO0Nz8GQsqu1lEFtQgJstqiIlNtwONIxjkg99NiIJQ1lc5aUosK6SjbNYvXgx7eZ7RrE1uUaDlWPQfkfiJFm2jyV7V1QJbUItD8degBDbMroDPWbBDZRRL3o2rXWNEmWo5VzxCxn2jWUD/SaIuCuoaObIkzaO2thqUfXURJj8cqSkGF0t+CHGQYxSA7W/Z+MmYRWte1q1+NtNrE/ajXrB2tYqAAMeqzX32yGBmMUQuygoHQrZ/4WSEkErtW8LJu73utIzIfFRxr7LyE2k/kLUTBNmJn799PY1wBnQ8H9pMpAwWyqG4W0WCDotU+IHUGcw18pKPWg5axgb3gLqI9H+32zbKG7iF3YfRXVZPFSJGOzutVxR/pMJDoyrZoJAMBHY0u2jGSxihQjG5fnlEdoVY7zqdVu3m7vB70IOhj0SCvoAtesug8y/F28gJI+2OvByE4AxnKWutoil4A2bnP3mGnjQ3dH2m/PFAvJkh0Ma59w26q8r9B7/8B", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [subscription_id = nullable text, customer_id = nullable text, plan_id = nullable text, due_date = nullable text, failed_attempts = nullable text, risk_level = nullable text]),
				  #"Changed column type" = Table.TransformColumnTypes(Source, {{"subscription_id", type text}, {"customer_id", type text}, {"plan_id", type text}, {"due_date", type date}, {"failed_attempts", Int64.Type}, {"risk_level", type text}})
				in
				  #"Changed column type"
