table mart_migration_summary
	lineageTag: ad186387-966f-5341-b3a1-33e8a60b7369

	column legacy_contacts
		dataType: int64
		formatString: #,0
		lineageTag: 34c7a2e2-0f1c-53e7-bd7c-9af9fb7382de
		summarizeBy: sum
		sourceColumn: legacy_contacts

	column migrated_contacts
		dataType: int64
		formatString: #,0
		lineageTag: 1ed07ea3-395e-5e5a-b976-ecd44d053e4b
		summarizeBy: sum
		sourceColumn: migrated_contacts

	column missing_contacts
		dataType: int64
		formatString: #,0
		lineageTag: 753f0b6f-3894-537f-be3b-0b3d447145e0
		summarizeBy: sum
		sourceColumn: missing_contacts

	column owner_match_rate
		dataType: double
		formatString: 0.0%
		lineageTag: 3c4d2b6e-fb98-553f-85f1-c74d8ec6941e
		summarizeBy: none
		sourceColumn: owner_match_rate

	column source_match_rate
		dataType: double
		formatString: 0.0%
		lineageTag: ca5f6b84-99e1-553c-a9e4-d793b13608ba
		summarizeBy: none
		sourceColumn: source_match_rate

	column stage_match_rate
		dataType: double
		formatString: 0.0%
		lineageTag: bc7017cc-cbb1-594d-8dde-fd2e8678beb5
		summarizeBy: none
		sourceColumn: stage_match_rate

	column duplicate_crm_rows
		dataType: int64
		formatString: #,0
		lineageTag: ea14e698-2ce9-53d4-aee8-22dba7ebd2a6
		summarizeBy: sum
		sourceColumn: duplicate_crm_rows

	partition mart_migration_summary = m
		mode: import
		source =
				let
				    Source = #table(type table [#"legacy_contacts" = nullable text, #"migrated_contacts" = nullable text, #"missing_contacts" = nullable text, #"owner_match_rate" = nullable text, #"source_match_rate" = nullable text, #"stage_match_rate" = nullable text, #"duplicate_crm_rows" = nullable text], {
				        {"7638", "7600", "38", "0.9526", "0.9222", "0.9871", "138"}
				    }),
				    Typed = Table.TransformColumnTypes(Source, {{"legacy_contacts", Int64.Type}, {"migrated_contacts", Int64.Type}, {"missing_contacts", Int64.Type}, {"owner_match_rate", type number}, {"source_match_rate", type number}, {"stage_match_rate", type number}, {"duplicate_crm_rows", Int64.Type}})
				in
				    Typed
