table mart_revenue
	lineageTag: fbde6e13-7211-5343-8e47-9c898d3f1713

	column booked_cents
		dataType: int64
		formatString: #,0
		lineageTag: b02437c0-ecf8-5373-b7ab-2f871abf38a6
		summarizeBy: sum
		sourceColumn: booked_cents

	column gross_collected_cents
		dataType: int64
		formatString: #,0
		lineageTag: 5422596d-a848-54f4-bde9-5c6e9b7b9f26
		summarizeBy: sum
		sourceColumn: gross_collected_cents

	column refunds_cents
		dataType: int64
		formatString: #,0
		lineageTag: ff4dcbca-5d13-540a-a4fa-678991df8b98
		summarizeBy: sum
		sourceColumn: refunds_cents

	column net_collected_cents
		dataType: int64
		formatString: #,0
		lineageTag: 533a15ec-b383-5627-8dfc-9578f00ecd85
		summarizeBy: sum
		sourceColumn: net_collected_cents

	partition mart_revenue = m
		mode: import
		source =
				let
				    Source = #table(type table [#"booked_cents" = nullable text, #"gross_collected_cents" = nullable text, #"refunds_cents" = nullable text, #"net_collected_cents" = nullable text], {
				        {"332340000", "319080000", "13345000", "305735000"}
				    }),
				    Typed = Table.TransformColumnTypes(Source, {{"booked_cents", Int64.Type}, {"gross_collected_cents", Int64.Type}, {"refunds_cents", Int64.Type}, {"net_collected_cents", Int64.Type}})
				in
				    Typed
