table mart_platform_comparison
	lineageTag: 2e872c4c-8498-5deb-be71-bd41b1115770

	column platform
		dataType: string
		lineageTag: 17d61523-7a09-5e2c-938a-9b1127dc8f84
		summarizeBy: none
		sourceColumn: platform

	column spend_cents
		dataType: int64
		formatString: #,0
		lineageTag: 40854cbc-d68d-522c-9af5-dfd2be7f8b62
		summarizeBy: sum
		sourceColumn: spend_cents

	column reported_conversions
		dataType: int64
		formatString: #,0
		lineageTag: b1aafc7f-6179-56c3-9ff6-d9073bafa5b2
		summarizeBy: sum
		sourceColumn: reported_conversions

	column reported_value_cents
		dataType: int64
		formatString: #,0
		lineageTag: f9ee1478-7718-5798-bce6-65949d17d5f3
		summarizeBy: sum
		sourceColumn: reported_value_cents

	column warehouse_net_cash_cents
		dataType: int64
		formatString: #,0
		lineageTag: 74da0236-72a4-56ad-b5bc-11bcaced4406
		summarizeBy: sum
		sourceColumn: warehouse_net_cash_cents

	partition mart_platform_comparison = m
		mode: import
		source =
				let
				    Source = #table(type table [#"platform" = nullable text, #"spend_cents" = nullable text, #"reported_conversions" = nullable text, #"reported_value_cents" = nullable text, #"warehouse_net_cash_cents" = nullable text], {
				        {"google", "12489881", "157", "108360000", "72175000"},
				        {"linkedin", "9197296", "79", "71100000", "54820000"},
				        {"meta", "26552128", "280", "192960000", "86430000"}
				    }),
				    Typed = Table.TransformColumnTypes(Source, {{"platform", type text}, {"spend_cents", Int64.Type}, {"reported_conversions", Int64.Type}, {"reported_value_cents", Int64.Type}, {"warehouse_net_cash_cents", Int64.Type}})
				in
				    Typed
