table mart_campaign_performance
	lineageTag: 1918ebad-1a83-426e-97b3-f90924ab54ef

	column customers
		dataType: int64
		lineageTag: 9f7152a3-9b69-5b28-bdda-b153452d6ecd
		summarizeBy: none
		sourceColumn: customers

	measure 'Campaign Cash USD' = DIVIDE(SUM('mart_campaign_performance'[net_cash_cents]), 100)
		formatString: "$"#,0

	measure 'Paid Spend USD' = DIVIDE(CALCULATE(SUM('mart_campaign_performance'[spend_cents]), 'mart_campaign_performance'[medium] IN {"paid_search", "paid_social"}), 100)
		formatString: "$"#,0
		displayFolder: Acquisition
		lineageTag: b9dae14a-44ab-4412-a8ae-4b25725aed30

	measure 'Paid Leads' = CALCULATE(SUM('mart_campaign_performance'[leads]), 'mart_campaign_performance'[medium] IN {"paid_search", "paid_social"})
		formatString: #,0
		displayFolder: Acquisition
		lineageTag: ffd52fbc-d531-4a79-a6f7-8fd8872d0f57

	measure 'Paid CPL USD' = DIVIDE([Paid Spend USD], [Paid Leads])
		formatString: "$"#,0.00
		displayFolder: Acquisition
		lineageTag: b2113b59-a7f0-4af0-aa55-005b360744f2

	measure 'Paid Net Cash USD' = DIVIDE(CALCULATE(SUM('mart_campaign_performance'[net_cash_cents]), 'mart_campaign_performance'[medium] IN {"paid_search", "paid_social"}), 100)
		formatString: "$"#,0
		displayFolder: Acquisition
		lineageTag: 38effb11-22cb-4bf0-817b-d41a4bf60531

	measure 'Paid Cash ROAS' = DIVIDE([Paid Net Cash USD], [Paid Spend USD])
		formatString: 0.00"x"
		displayFolder: Acquisition
		lineageTag: 9f444e3b-83e7-4f97-8d7b-d32e08ca4e24

	column campaign_id
		dataType: string
		lineageTag: c28e3d0b-99d5-4ca4-817e-4f3b93644a40
		summarizeBy: none
		sourceColumn: campaign_id

	column source
		dataType: string
		lineageTag: 48cde02d-97f2-4912-b329-6215c5598ade
		summarizeBy: none
		sourceColumn: source

	column medium
		dataType: string
		lineageTag: cf3a8216-8a6f-4915-bfc6-2d54c8310040
		summarizeBy: none
		sourceColumn: medium

	column spend_cents
		dataType: int64
		lineageTag: 75006e8d-1f12-4352-a714-91ef6a9c1f9c
		summarizeBy: none
		sourceColumn: spend_cents

	column leads
		dataType: int64
		lineageTag: 57705dad-2c67-43ea-8412-f86a634acf05
		summarizeBy: none
		sourceColumn: leads

	column mqls
		dataType: int64
		lineageTag: 3c276623-266e-476b-9f65-5dbd28dac503
		summarizeBy: none
		sourceColumn: mqls

	column net_cash_cents
		dataType: int64
		lineageTag: 318fc966-3343-48be-846a-f93de0a62de1
		summarizeBy: none
		sourceColumn: net_cash_cents

	partition mart_campaign_performance = m
		mode: import
		source =
				let
				  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("fVLbbqQwDP2Xee5KuRCSvM5Df2JURQFcFpVJUGAG9e9rm4FRd7vLg3FOnJPjE18up3FIH9ANKbSQQ2yup5cDwnSKQxfm3A5xxJWX3ipfY2acxKgM55pC5ZTA7/T2cjn1OfcjhKbEhKchlvY3lmzoQbrDWngjrMJMKinwV0virh2xSlWbnfUKSwxTyfME7TKkPrznW+qgYB1t/aVWGmestESmrSWRjq+xBkNlK3Uwf+bbcmtgJwz9behI6APHLJc+pqENd9zIuCad0jlmMnRDVdE1qvbim9yCofTAcldohhT/KbdSwklj2AdvCaiZnoSrWgjzh7spp83gvuR1+Y/BXvvKCU/Emn/acKS3U8LLQ3GCdR5hWdCBFeBj/MSCJ0YurAm6ANc4jLsHwnPjlWOVhFj59ODR8kNiyDMWPG2AO6TlQaT5vSXPkqIgK1sfPFMsS0JZU+7aOC/cIiOYFXiHUuKuSGu2UPNAsSDtni2+nn+dS44d4q/nH57ASWn4pJB2s4fiNpz1U083FJxBRI8EXwN2BW5zhrug4Gv9fSoakhDufMWPs6CUMDj4fJbasSyGjd6Y3r4A", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [campaign_id = nullable text, source = nullable text, medium = nullable text, spend_cents = nullable text, leads = nullable text, mqls = nullable text, customers = nullable text, net_cash_cents = nullable text]),
				  #"Changed column type" = Table.TransformColumnTypes(Source, {{"campaign_id", type text}, {"source", type text}, {"medium", type text}, {"spend_cents", Int64.Type}, {"leads", Int64.Type}, {"mqls", Int64.Type}, {"customers", Int64.Type}, {"net_cash_cents", Int64.Type}})
				in
				  #"Changed column type"
