table mart_paid_efficiency_daily
	lineageTag: 0c718239-2b95-598d-a80f-4172baaa8bf1

	column day
		dataType: dateTime
		lineageTag: ec195778-fac9-505c-84d8-023ad4dfa926
		summarizeBy: none
		sourceColumn: day

	column campaign_id
		dataType: string
		lineageTag: a9d068a7-bdfc-57ad-b662-a9e357a1badf
		summarizeBy: none
		sourceColumn: campaign_id

	column platform
		dataType: string
		lineageTag: 4a344e0d-d06a-5f68-8a84-d4670bf7d237
		summarizeBy: none
		sourceColumn: platform

	column spend_cents
		dataType: int64
		lineageTag: 822f9efa-fe3c-5dcd-a59c-03eec0260c30
		summarizeBy: none
		sourceColumn: spend_cents

	column impressions
		dataType: int64
		lineageTag: 9c104b8d-7900-5f5a-b32b-28f80011ba9a
		summarizeBy: none
		sourceColumn: impressions

	column clicks
		dataType: int64
		lineageTag: 7311919d-d00c-56e2-9d72-08eb21571a8e
		summarizeBy: none
		sourceColumn: clicks

	column leads
		dataType: int64
		lineageTag: 1e866d82-a00a-53d1-8c1f-580867a08d69
		summarizeBy: none
		sourceColumn: leads

	column mqls
		dataType: int64
		lineageTag: b7a77c26-5e8e-5a35-87ee-558ff0f0de92
		summarizeBy: none
		sourceColumn: mqls

	column calls_booked
		dataType: int64
		lineageTag: e3e3a6f1-8e4b-5ca4-8303-60c0654a2296
		summarizeBy: none
		sourceColumn: calls_booked

	column closed_won_deals
		dataType: int64
		lineageTag: acdd25fa-96d8-5cdd-a744-f3201726bfe2
		summarizeBy: none
		sourceColumn: closed_won_deals

	/// Paid media spend in the filter context, in dollars.
	measure 'Paid spend USD' = DIVIDE(SUM('mart_paid_efficiency_daily'[spend_cents]), 100)
		formatString: "$"#,0
		displayFolder: Paid efficiency
		lineageTag: 8da92ad0-ad98-5d73-86b6-3dec14da4c96

	/// Leads created by paid campaigns (activity basis).
	measure 'Paid leads' = SUM('mart_paid_efficiency_daily'[leads])
		formatString: #,0
		displayFolder: Paid efficiency
		lineageTag: 4f6d87e2-3084-52a0-8267-60814fcfd584

	/// Cost per lead: paid spend / paid leads in the same window.
	measure 'CPL USD' = DIVIDE([Paid spend USD], [Paid leads])
		formatString: "$"#,0.00
		displayFolder: Paid efficiency
		lineageTag: f5db4883-5c4d-502c-8c82-dc22b2ccbb56

	/// Paid spend / MQLs reached in the window by paid-created leads.
	measure 'Cost per MQL USD' = DIVIDE([Paid spend USD], SUM('mart_paid_efficiency_daily'[mqls]))
		formatString: "$"#,0.00
		displayFolder: Paid efficiency
		lineageTag: 73e805dc-87a4-57b6-a666-82cf2d0c9912

	/// Paid spend / discovery calls booked in the window by paid-created leads (CPDM).
	measure 'Cost per booked call USD' = DIVIDE([Paid spend USD], SUM('mart_paid_efficiency_daily'[calls_booked]))
		formatString: "$"#,0.00
		displayFolder: Paid efficiency
		lineageTag: 2208a2d1-9a93-537e-8f8e-8190d56a9ac7

	/// Cost per thousand impressions.
	measure 'CPM USD' = DIVIDE([Paid spend USD] * 1000, SUM('mart_paid_efficiency_daily'[impressions]))
		formatString: "$"#,0.00
		displayFolder: Paid efficiency
		lineageTag: 887ca634-6de9-542a-aec2-611adc49fa14

	/// Ad clicks / impressions.
	measure 'CTR' = DIVIDE(SUM('mart_paid_efficiency_daily'[clicks]), SUM('mart_paid_efficiency_daily'[impressions]))
		formatString: 0.00%
		displayFolder: Paid efficiency
		lineageTag: f1e62e33-8c2a-5f79-94d5-a91dcda98554

	/// Paid spend / ad clicks.
	measure 'CPC USD' = DIVIDE([Paid spend USD], SUM('mart_paid_efficiency_daily'[clicks]))
		formatString: "$"#,0.00
		displayFolder: Paid efficiency
		lineageTag: 4ad2cad5-b708-5ef6-994e-16c458881ffb

	partition mart_paid_efficiency_daily = m
		mode: import
		source =
				let
				  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("pL3bDiy7kR34L/3sBhjB+6sf5icMQ1C7NT2NsSVD7hn//mRxRWZlVWUE19E8SPtI2CeQWUyScVmX//Jf/kmT1n9O/Z+T/NN/+qf/4z//83/++9/+/K/HP/6Pv/zHn48/pA9Nrz+163j9Wcrx3/n4T7r+81//01eYf/vb3/7tv//lT//y9z//9V//9L/+8ue//7f/6/p/j39oZfRXqFxff7lPOuBf//ZXxPy3v//tf//HR0zNJb0CHaHb63/W18POOOrrFf/0P//+t//1P//y3/7j3//6b3/6P//2//z1X//y9/fbZ815ruhprj+1vp6fCPv347/+/m9/WWH/91/+5d//+udb2DnWD9BT0/XHR7yfmPq8MPX4119/ispaGFmvH4fZLYy0tTA6XnHq659f/5ZsA0YLk3p//c2SdcWezZZb/ajEwshcf1O1r59Sy3rQFD8tsTJzrG9S9PVrjs/n/ImZn1emzTLXzyhYodz2YXYr0+Z6wTzL2kAWULcBo5VR+2ZaGmvLrG8yjkptmZnWljn29+tP7HX5+Dif44YrM2Z+PWXL69vsEu/D4qzMaHmtTCp1PVWzVw7CbFamy/pipKwPe30xxf8NC7cypfTX89U018r0YXtG/KjEyuS5jvBjr+T1iPikhIi7Oc3WX+wpfZxmTszqXDO6Tgk5Dtz1vdQaf+KVWBnFylSsst5+QwkDhnumtLH2zEj4nxYteExiZdLouF5SXWfFuhda/CMSC9PXV95mS+fCBMd5e16YIThVda7tLOvTqR9r/BNmtzBlfdDHGr+WetxXOQ4YLYyI9HXN4KJeD1v9nd3Iw0zyugN01vWYa5m6/xU1bmEKzrJe5PwygzOjO/e/pPWLpT6wMMnCiB9md8uMdX5JWS/dz7sgbwOGC9PXWVYqrsHS47Oskzsmr3RPpa27VtfZU4mw4cJIkhW260p62+ZZh7NlUrctk5Dn5viyGsz935FKrLu1l9tWljBgmJm1dR8UnWul12NWf70HectYvpPbOim1zU1mNtilWUfucVG84qxvflhA/Q06naXRapslI0U7ywTnl5zMNSNrKer6BEeN09tJJgB1FTAVGYrWHOcpk1uaYw+uU6y0VnHt2I+YN2F3p1nDabb2zLxd3L+/6PoQHu//ldcd9z8yMz0/xuffcYXZVjNTsMZrS7fw+rsHDPfMWJuv5IJUSu4ft/O6VAKAi/9ITNMVd7qX4jvsJgEY656Z64cYEpYhIm6dKVZnrpXBnRWH2SYAyCXq+hFxPfhfDNkAONZ5nWaIfXzjt0XR56hMAjAlI5/AfbP29/zITZ/DxsVMW/u6Hb/A6zOfYWoqTgOg9fVhH0UcEvlS4y+caAD04/ReC7Nq9XHvJkgYMDzL0kQxs6pN5LZ+Zi9kA0CR4mlO+l7v/pECPYfdVJnrZGxlVaUtbk1J9lJm1P1HyoyFyWEaIZlZmImUGQfDmZXlbcDwLJvrKzw2DO7/+3Uqz1H3C6PHL9iRkKN9shqGfnormbz+EajnleaPefs5H57Vq/87mlAyCxpd97PMCbPNzNYtKnldMC2HZYeQ9f9RZa2ioKyvWlein+PHZHpmQ1FldmydlaV2f8HJ8n+uzkeXdXOtosHPw6V6WwZtIp0rwZWrFxWE2TZmEooZ1GwzXhi2/JfVgCtNURb2MLOXyqbMgpZZq+vP9SkNf73Z8r+tLtlcBea6/T/7SB8xm1dloiRMwzpmejtinTC7HVPR4snr8VYroN3eVdyA4SWDyqgmZDklboYLWf6XkXC5jIaFwUfqn7yNvGVWFdLyRBZwKxkeflKv/ldF8jnQOUs9bE1Ipzpm3Rb9XJns36id7ZgpuszrMXVlSMEBQdb/Uif6/7Why5y+q0xx4m5qmZWRtb7aPX1+tVS+Yjr1fz9vl7EyHskaf4xM/V8QMq9cop15jrOXyfo/oxlTxgp63ApxYkbW/1LQkTkyMoQtdvDIJmy8MHWdeq2jzX5vQj5k4U7132W1JESRhIqWuCKazMJgPIq2da9h81vI6l/RDC+tfDaZg8dkasyKaYIMNNevz7I+f0Vc9T/KysVaateX6X9D6lT/rc71KR+PhplECWtMTUzGvKYSxzG5LsER/oRKVv9HcrsOxI7UVvV25OpzVKaUQVb6Gn20j8sr+BGJhRkrR2kZY5kRDirUm/73ih5K6/NqMvuljFLT/zLeR9l64+reWirsjlkf0LFjCtpnYS9chSxl+iqHVRQtzSa34l+CsJvifzURmqLGTGHDUNXrMVuNOdZDyTXvcB6NKf6xhY+EWc7a158NKln8H/tvJcxlHdmqOV4YZRPmiikPfkqdcTdYyeK/r+SkYV83CTuQ6hT/vVrzvwIEsPrMfomgzPDf1hiJ1E/zX9yA4cJM7Jh6S5j9tEzJ4X9RJMoFHxHOYL9dpuTsf6yPvSmmHzMcGKpT+1e8qQiwHWj9+2m3MrW/WEEw2v3uy9uAYSWDy6VKe2dlfiWs7Oy/2/gtYdiD47zFvyJzlmGSKeujXzOLYHdX7/bHjSCWL8sJ7lA/zB7J1N5IpiZhWqZk8Z/RFSyjI3+KkXBayUsGGaRKWlmPzL7/EYmFqbhkUHy0FCa62jzsn2TD/uVr9h88GlP8W9WqaBql+JIhi//ccJZNfOOz3Ha2PkelRswZC9OAt1qLP10ck5Kzf11fT2uAEsY1lzq1fwPaSF7ozPVnio9EZvbfsTBlNRtbjHxTsvbPY9XlZWLHrPNB/YUha/9aULhVpLY26gn2dydvmXWCtwz0wyZTcWf/0xqZ63t4w2WdW2Yw0zKMRmud956EPvYklJ39z5XglYwhvcbgICVr/xN9U5AE4ZY5K48chN2cZcBDCVoAKc5Upgf9A1xGE/4sug+zrWS6NWXm+cGoXwxOdsC8OiLFcHAzx5cMWftrRWf5+Ae0FM5u8HNvT9nafz1kS+tbb/EcNycvL0MHRZLhmGrYLctU7T8wLVvJd5fwjM107b+OmAI4s35MW523ZRamrWznWJj5Tvdm/LDMJbNyiYaUt2u4ubNT+zdRXC7VBv81vKwzU/vXZq3/8d2UkTBgeMkAM1GwwZV5W2ZhBhAeuWBgfQFSqv+wFIp5Jbd5nYxtBJt7uJSMhiPiOMqAPCo9aG4NipLRbfMVjJ6iHTNoSkZJ656uCUOUfhbo2Y/K5Mto4h4HJVDMxn5wFnywnIzRAa0HaLhJMOYaLiejo6kqmm0onANqx+A4GWUaWSafZ9l9EqxuwPAsS0jlK6D6ZfMd6j+GlVkbZzoF8aApGQmHBS7bFmEphkvJMNjAq5H37soEb8x0ZSZao2hn9h6cZYOnZGDLlDrGBcnwssfxBygZYiwma5dFM7jBMjJmQVemy7jj/pyYHiKjAiMrHYN/LUHXbZCMjIIMDySrHuDVB8/IqKteq8AHq45bYutEZSqZjOSkKkrMcdLL6ibsrl020C6TkywkH8nKR8zqDf67Df6RiErU2xkUIaONjAbzuktHDkBMgydkoAVc+spBVdLXPEF/o1JQGUFddI5mxq3BnJ8fltgxbSW3bayqHa0pp58wXEJGswpT7GK44Ajqh9limIzbsZ4r5FYNnpCBZS42Bq4a5xSNvP0Heh0C9pICxn1um/z7eTcWKzOBlbmAj14DabiMjN6MPtnQx1ztju6f3gwio6ADVwF+6/YVOr8hi8jAWVbAKVTp8QfU2YQZZ1gumFCsqm76nzfLyMASHxd4vpOFnWcdLiKzGCJTPhAZzvHNIDLwIx552bw/V9kGDPfMWP2TgoaHthLfqSwjYzb0/jHA1JICoudgCRmjTLSWgZi9J8wPB+TkMMwygqp6cHyMjK5yxVl7zz81DLjJy7AwA2yje4biRGUOM2TeRykzPxcm+BGp4j+j+E/ngN2vjjw+RkOzVl5dAEBmAlrH4PgYA6lekav41/i5mHYZBgkFGRkOnex+PywdQwBHfQFx2lUgDfdKJOkYowK9JUBk1DAx9egYR7aNowzAKjSYm//GTFemAWGU1wezjp7hLwxZ/Ke62jEFKGNc/37BxdIxMnrAL6QsEDhX6z/4FSkKE/h+68wY8e3g8TF6S6Au1V6vUmb6j8YU/xg6WbLT2lcm7weMhzKYIUzc0yWH3SOWj1GbUdVKSR9M2bwJu8mYgcUAxnWkAMQ0XD5Gs3c8UmdcMvk2X9bnMFukLLZMXUveN2cZC8kAJuH4AQUN56ARPlg+Ri6joGEN0RHwMYebqghb/IPV2vOVMBf/Uy9eVwb7V3N/U8uC05uBZIDGeuyYcc5kgh3D0jEmSP8Vt0FqYSOTpWOkhltfJi5XlQDCNWg6BgiKPQHB/JmkfFdHHh2jD3D+tKP1X3vYlRGq+EdxhJN2ky+zdIxSBViZhMF/DttlLB2jogd83FmYKIwZDLYGTccoqyo0ClJvASRlBHSMz65MqvHhzagxJEOXgVd972NqGDC8YzK6MgP9Lb3nTk5UCl0GalkpSOtTCYBCg2VjHOkYariszFnmFf/ZGOV4c0jriH+WMcV/wmQHkiM97uOxdIwMuYgCCgq+7fyx5j9RmbMMvMmXpFC/iDLnt1me356ayQD3Nz7SH2fLOLV/hTCYiCFm8wgnCBQb4wMr0zd7kK39azakbLsY4D2OyiTMkBp5IXHKdUSK+MkPWfxnrPBcXdymAT9xuHSM1pNtFZuapYCjNyg6Rk9iW0a+a8yHLcNCMiZIfxkQj+vMVf8xqaEMIAQZPEUomAWFHAvJWGftkelemj/FzVQ8OkbFLPSVj8qF+ld3fRk6RkMiL7fBd3LflaVjZED9ClgjmDf6WQpLx6gV07KKRhJIUjP+EZkOM4YyM5f7VMp5VE+LAaWbGD8Y6iDtg6X/E2bfxwSBqX50ZZyVZif/OYGNaX3MGX7aSkMyUGJmKzFzCY9Ilo4BcGIr8iP583tkqKvFkK2PWRuzMEzt34zZsVKypmFqy9IxjoR+wYs7hGA+Oh3pOSqFlMW4WrrRZeXWw9Tnt2ew5TgSZRUxoa7McOkYrco5XzZcZtiHougYyJQFEjCbuTdLxyilACuDmcwsYRrO0jGypWVGy8CuLP6xQ9b+CW8OZFSI4houHWNgkn7pyoV4zEHRMbpgmIDBaNcwz2PpGAIaXakmxVDjz5CmY6DmL8maMhIw/gfPxlgfe4N6Yh1hXuqyMaDfIceP2S/Qf47D7GF/aDC3fp9IPGOYWDZGyZAiTNiBfewfk+n8qwn9ZggySQz0oNkYlpUBkdHCCtNjYxxnQzHBP7kksvy2BMXGgByvgFh1jRudRIcd/GN6WTAfxI7ZvC3FXgZ2ScZtI4q6SA9li3+k30dF1+4Js3NoeFoMwA2IFDxRbuEEgeFjHDc0xpjrE7twf9l/LiZhlgqoLE6fPsIePcvHyGBZ6VETlguBK0rE3XQy187uCfD677L9K6fwtBhs06jiuik1LFUpPoaFqqtHOkrYYmb5GFoqCMxQ3ZTNNUNW/4rx+pEpg+AxSiACM3g+Bhh6CTOe+jGw/ok5PfmSYp3M8U7M1M+YGT5GNsqt6r3G3AcMi/+M08wUxscMG+rKTv4hY318SZY5n4o/z8A/lo9hij8m5d3D+ZHHxxhJTmb5AA0gbGRmTonRcj055e783JblYwg0X0tBgj/rPipzlmVjlg8A//RbiEqcsPFRJqtDYcpHH0X2w6N6k//cbK6MobDEsH+Gj9HFTB3W3dpLmMmzfIwEIkYBj04xWXevVJaPkVsyjAyGMjNu9pB8jAleR6sosiP1kunzMaZ93ihiYgbT5CwyIFty78p4c9HJ8zFw5NYEDliL9EAnbZFxIjEVdh6wyBjxwzKDf+yYAVbG9zBFPmN6FhknRDYZ6n8EDaPJ0TEGqCYAMX1Il8YB4wYzaLLWcMw9SCkmTcf4mZaNEyuTN3E3K2P9GKgHl6DKnr5Fhh08cnYfiTDbtAw8YJBPrufK24CxeLnh/vSNA/M4npPlY7woTNUoTHrh/spH6Oew8cJkqMo1TMs0gJdNn49hwthHotwuBpP6C8O0ZTIKAgAyRw8QnpPmYxwVK2D/GDDnHEyCJ83HSNYXFXB7FENcdRCZk3bIwP622zZUop4uIaPNapqlYrTMLwSB/IbZtphxmGGY10eArZ48IQNiLQXKUZolvrtYh4yCs1E6uhRa4pOX7MugYd2Age8RLWq6hIxeMkrMAvGyMgJJq8kRMqyTifF82+xBti+jYGgDgQOm4iYqU2JaPqbDbpsWKOpPlo8x4CnToOndIhGF6TtkmMNNmvreMeI/GqOSUablZR94RCef6GwnE+o5CbW/tgCyPnmHjA42psyMFnP90gcVJ+yO9AeBTHSav3vDXzE9SEazCsY45XkEjKNJ0TE6TAgEqls/nnLqBoznyxD7Nyr4SEELatJ0DAEJ/kiUy9t3Q7yewmT5GBOssuNEG+c1G9QgnkKmkVp12Lh+xnkZBclAbxS0oNGC/tuk+Rg5QYqpz7eobHOwUZP2xzgOMStZ0QTAHNMTrJksIWMM8DrzOhtbCcsucTEZBmPSW8Zc4jDbPQOiLLRBZgqvf5aQYeTvgukRumbd/bZZQkZBz1VPdwckp+qwyyZtkAGmXhvrAG4tGCHNyCBD7wYZogGMaXIGGeg7Gby8xZuQZWS8PBPXykDUUiOS4+QNMkDgPs5Ks3dIX1KM4oT9AzoZvYfFnGuQMa33jwtGsgSdqMkZZJhxYHlPMoM9yBIyIDR2ioyXON0jCRlH7gMgYZpGZdaA9TdpQkZel5b5UQ0JxKimT8gY4E7qidbrAbJzkgYZ0KmvYGqnsIPCEjKyGooZpUxtYXuQJWToNBgTxihvnodswm6Af0DLpHyRuNRNVVxCxoBwkna7syUQQJ8cIeOUQpHL6ib5C0NW/xlOFmXiMv1wqtXnqMyOMfOl1MGYaXJPzCSIu0mZMV3vq8D+0NZ5iOkZZKRiU5mZrh5zcJYx1b+hPMv6yyPuBtOMDFkN3ppW/1p730el5Bi6+W2Aydw1oNZN3iADPWaApH4E/76+dZeRYRzEYRTzEt/+TPWPCl3AKGgpPh5YRoYoxP5xGwwJSy5p9JZR2zJvfWfxS3WakoHvp5sRjMb721PJhL/mC5TZL1RGduZuk6RkwIcJDqb9fjzGAWMJk/XplG6ySfOrqyC/UbnErFhi1j9MZWQTdjcwM2W5cUr+BTfiIPHlM94zTP0PN5nj/l/aMvHAjDbIGADyGIpyjLClzlIySkemfBSvmMv0ODEjQRkwQjVJ6p6Dafj0DTKSMTEwoJAauTBOjpGhuP8NLdMD+MSkGRnHb4bGTOpXauv34VhGRsbW09zb291J/IYwSck4DjOxw+yiPvo3t2uR0YtZl5l3SQ+rBIqTUXCYmbRcoQPGSzORM8tbV95PAFhOxrG7k03/+yX709xrhrXImAlVZu33iZnzA7Dl//cUQX7DbA8zXFiwa+0jvGWUhmWYQXZ+m4wkf2HI8r9UM0I14NrlQ5E3YXdbBn6OsibsM4XDHo+U0ZMNZqS93f78/g5Fyqjmw9TyXVZdtwHDlekQZMiYic+4QciSMl69MiR+ljvXgIQzWVLGtJEUFMOGhIMZl5Rh6F05lTI0EMqaFCnjSOVR/7drlFmpgDH2DwaZNivLOSBHTZ6UUcFWz6A94tKZbvOaJWWAJdz6OsYuftkz1MMjZfRkjRlp6ZJj8juPlEeGMdWh2d7z1/3vB4wXBqm39co0zh9pUoZpMOc+oFnzMf1/OMrZ+h9ssK713jJzVsab/ht7WcqZocUrw9T/06BMuExnQMmcPCsD/ImT+VdH2NljWRkvqzoTMB0XQsrPxElWhiQcij2DAtDD0ZRHy2jzvF0MLSJxHsVIMlRM4eraLkPDsTVtkgF0fpkgy+q3IZj8RqWof5iPvYh2lyy6D8QhWRkDyW4D97ZLwCCZPinjpJfrSQH8chp9CLP3LgMqqlziKn6RxZIyjt8OBpnozOQUbxm2/EfD9bVl3gip/DHiew67S8wSaplymWT4dba6839bERDVIMcYJGbU/B/M6FovUqbfM6NNMhrs/rJ1UnqcMpP1fwVGQWvG8LrkG2ImCrtJzNbldTxx/1ZkeIjp1f9Drf+PzBk3oA8yo1gZkBmVvPLakfcPxlmXCpAZclH0u7+1J9uZMUm0AdGMqZsEgG0AQJ+og03Yv6ddn0E9XkZLpzcmejM50naYnE9GqbZprvuvuQNhlpeRG9wXYYDzngAEb8vcM2ngnoGqt+KCFPeiyaxJppiz3EXMcDoAklz8f62WmyWUM3LH3uhzmK2MGYiZGZ2j4Iv5CvgHWjMt+xfNGfW///tf/++//Ou///VP/+0vf/vTn//lf9z+rxViCFTR12g0i9+GOwNSEs/Q0ztu2TehYD5rhX2E/QM2Al19DZdXTHXVBIapCYwPpoc8P5pSvZ767vWMwPztK2CsJAh0NAzGAY/K/sLofqWzaUbDzlNbvNK0ZiS6eRVignrpWyf/52Q64VDLROO5B4qwr5iuYYTpCEIUFYlK8BMyLQqoghwnmN5pk7INGNZbGFFU6W8DgRJH3ax0wYy1oJGgI15pFvMAsZbjCNK36Gj/6Oo9h93Q6jqMp2Danr/QOF+npIt5MFNwvDCwQg6t/gyznXmg7q2id0k98Z+Lkm7Bk0FxU8tmTxdiT+NLLPB30uZnt2dAaqXVMJTSfmStNAi7YVDAEhzFzNic3i6GAtJ8OqVfp7eD7jzDbNEt2SjH6a62mfznovrBgtPbtI57fFLU/Uofn846JRQQx7QPSKVkeD5rIAGhWeJVoehlqODW3mkBfuQV0wNldJzeYj9eSfGxSIEySrmV/oHi71fAuPRfF2CBcrShWv1fsO1XugKAYiDPXUbW2IoV71shb6GG2n+2Q/mIuzPdAP6mX0ud/J+0u/ibavib/CNU74TZtqyRHpa8U2v5ChjTolYWVoA50lriD7szyTesMDGrz5v7gG0bmcKRAezf4nfOGUmiRtBIaXOlcCP7sNlXTE/Koxg40Tg4Ncc3CyPk2U5i8PxutKYwYJh8JwgTQNQacP0eR92stE6IgxS09DYpGasMWoEDzxN0cGMXPs+hPuLumh2mPF0vwEdwUnjSoKYMLiaCd9WAThZP+YJYUpYv6lb2V4X1BQE/vcA+SCOXjDPqblej6V/N03n6A9YzIDXZMhXYXt56zI4z30fYnUAPGEfrZhzxVe0bjSA/PpY8XzpwLQ6zHdIDC44hYZvhwcjyWgRLXMBiBq3VbxWtqLuVhnNgTcDpz/Dup51LTkiUgcxGvlljRWE3zZN1GxgwtcfnpOtcMkHDOG7C30Lrty6ieDKAVr8Ihd8ltT4/FzVcBrdKwSgcgVzNGXWXlDVMffED5IACdwakrFCMYN36vJJHf08Li7yx2hzQhzHiTe0Jb8DkXhI8k9/KzuKH2aLVUaabTKuGXR2WeaPTaIRQERg5vBSE6JOV2syOcLXmPwWtHgMym9qa3orPXXMNWxQklee4qdeh0/WN5Ql2tYflacWgImdxHZZapLkKsDyrOdBrmC2yXB6dsCjroHiO7KMwz6i78xtODtVIsoF7xxmQKqrNx7KAHJxmmOSy5CAIjRgXp6mPY3rF9BRbE5RaFURjyYGq8xlmW2mhqC6AxiQfbfwVMJ7aIv/WGzc4+QvDNMryqjgK8LKZCMjRwKbRwPJ1fg//i2TBRqipO8wnA2/QV0zP+3WgRSTApsvlfhqE2esmQX9xXQVDwpqIJRtJRfaNddFLESV4zG1LFD63dd0LWeOrn/eTMQvUBHHn5mNkPsLuoBj4GeFSMwLW8Suo1ykb5vMH8xMUWsnPIig3WRMOntem/uREeQFjfezVVDqS5XLZlmj8trulBsWolPXiOYWtW9qhxiyiCn4DjG8lucNLkg81ANVrUABs6kP1XjG7m38Xy79BL4unbQwdqqldCXN8uzpoGHCjUzOhUyOXc2CLH3OXf4PAWyZkdEvYP2H5VWUCLXr8WS9+lSS3VcYSrEDHNLRoj7t6HsGqTWuGJhCBtMavTPndmlZUbecn2Pw7kGyVlVqAH8AV2EucOw7mqka+WGbd979pE50OBmJBdxlwUX/SQTK25oTqpnw2pJxH9WR05zBUENgnJfnI2DPMdk4Nf4Oyvu/RwkkH7aFj7RP09d52oEHUXfoN4e6aZJ7nt8Y/H3NVW9u7oof7tpQpj+1L2pRnnTkNw+/Wwkd1CWAZvQ7pZqMb72mGANYTWhxAlPUUVjAsAUzrxJzasB2BdscZdbfSULCqMj5aos9jfpZRlka19nx+t0/8VJl1+YHdSIPbyKZ09RhlvTY7tU1sZJxYtyDONv/G8ARf4shhtkNTyqDJX8CMRR66eczt+PJU3LrGl/4sj+WoycCEQzv+LPNWzkgQdnNRQzQIgoQjbkh5FLUBkZaj0GryU1On5zB7JTQAysq4szqfSxjaN6gCOmibWnPYz1MGUNbQKKsmRhzefiznTeQkBJuF1/3nzL9nBd0om/CIgIxniXe1hyiDUJIYLx/2HX4VSJHekl366+PpgePkV8CNRdS4WUTtbqtMoU/qDX0i4dXPsuiOy0Dtces1ehsfnfXnsJtBx9r9DdzJC89Tnh+1eDU1TkJRswKt4WiHsjZKZm20qoyLqeQcYGSjrADLcnyXcuU64qaOWpicDAr/yCt+0LH6G5DifhtmEGpRyB1H/PZM9l3BMAbCesS3v+eTPK3pPYwX1OMUikKUWXUOwJv4kpNfAcOSugGcVW/O4v5YQhlEGdRUKigNecT5BNsoq8M85OUtuCny0e14jrvZ1OghWJq7yZu9RpnR/I4KC2dujr8YplGmGGllqPzJzS5XwoAxzW+av2+/HP40fttdTpbW2XrSBnrY/WZ5gxWufi+8ml7aKsXFiZC8wQmdKDM/byMctLq8wWETLWxBEDp9RAJl5lSaocjLeVH7KBGWN5iGlJugQ4oB5Ur0yY7HXJ1a8z+Pe6y0O1SCmkpuAATDZSTFy8Kk37BUA1Otzzj99iBlBjqx9BYM3mBlGCKiGeYApDZKnCjTfTLMxjBIR63q9/qV6ZPBRK4AbZTz/r2Zlmgy0VdwWgx8m55tjT7i/oHud4/hE67fVLVkTG5m08VFuynVKBMTfJdvWf84YJh+Q3aoNHS0dNNCmExNbS7J8JuOGUYsVTJlnBHS01tNfrhzI/1HGmW1h3Nqlyg5jLeZzC8pxmpTBlaXEfa439TZfy7mpgbuuUClFvrs/qbORKMsIx09ykH9RpQ5j8kUWtOwjQPIt67hnJp2xIKxD/RaRorf3SVeYinESqzUvpwX5DfMdniJezSj0JKwpGYdsXQi/bYxQo3Zc5nokx0nbcIpcZG0chyQUgxGwy3BZfx99uTH3hFrsQVZwzbf9i/e8SMuxbYb5lsxlJCPU0yew/whPHCvAftAaIrtkUF0ILXbhf32UiihKLa9rZ+sQgElT9895wxIyXaaNnQ3jHrbrwpDvFzJRIMXXw+kX14xXYot+LBiGtEyg5JaOM+uj5L6wxcyDrghaemNpCXJt688o25R/gNoFk13im3w3hTKX01sCniyKQE3XXgPMKiAzfWoP2obX+/uNURTxV4Wo9gG+ntnmO3pjSYo8FojBbmT0BRb7WY1hYwszXivMMjBiVmbjHafcgSPycmKVpMVBZ78roGmz6vCeL3CWgvSAW0GPWvxTcWayYlNNEa1BJQqoSi2DTefIA1tOUCeCE2xLaDYVlCLUL5s3naXe6vcHGRyoBd4BqQcFzGkVlAntl8kaR4/gUsrb+BJfTY+e8WsroBMMQEZuQRkgm+bkyk3x8VreC5UwPCeBuOrwOVOQ36oUBTb40PMKKjnvXcSBKR6J916J0aqHgENSmiKrW3msha8R9NQ8V3PTnONAVmavEnsmH4o5HeOlZY7dlX856LMNVZ2fJprtLR/zF3uncWsuusdDZz8x6RW2jSmKia2s3/b23txN8l3wQ29aunRA9yS+BTbXkxIzaYcM0DkCUWx7ZAvOo2HN5uadbcHZr4MYEQ1ovgJRbHtqIQqxMVzDcZuQlNsBc28o7xCg6OeZVbxn5MSZq3ve7GVePO4wuyp3CXzUgvAO8IZswlM2cs6cLvENyDbD8WEtQqm063H3w/RD+2GRMTGyy2o+4Wm2Oo0im3VN2/ea5IJb/QG2k56J9/iL5Gn9CaGQrCVrhp/24zQm1aUWauI6CUuiMh2qEBGpGQoEOQZrzTTDoVKVxn6o2+jz49JNcl6ujfJavVtzz7C7mYcEzOOy549u7+oS7BtppU20DrJKeifC2ccl02fNF+zc791whJsj90huFb7zjf2jLq7qJspGUEleITXAUuw1VZMDBrl1jgFT9+NsuewG9xgQ28iX3pvfpLiGtGhKpdX5/tSom/+T0g1ydRq87qDDQpNsC1qKBGkZFPCXJkh2B4H7crrChxUNivNOtuBQ/Vif42rHSrZ7XMI2w+doKVDr7OH565HsDXygSRzhUwjIFQJZ21XKjQ/ga+pQZdfeIIt+rWlGbBD4pVhCLazYFMbwcb3yjkDMsd3thkHWEaYxYx4VRgVY0hqgs/y47/7FdPj1+KaF4G/G9ymmr8HGdigCanUVZ0PCbt3NL8WP91x5varUq3xY24ragMt4epvYcdf6C5ZOyVegTC+6yNoEHaTfMPVpelWXFJcfm2rYCaJ8bMk7p1w5ntWnGs+Af4lfi7m+LbpbIJSkNYAOyAUv7amCYQRYs39z8esNNLkY6UBl0z5TsWL4m6WGlIY1WYdYT7qEmzBRHuByd7OZMEVSOEGgW+Al2id4fSAJdiqEWz76fF6qzX0OepmqUdaOVnNOL43CQXZJjuuF9RXNmAdPcDmCW0PaPOihgsxrlw9fm0rAPgLJm2SSzgVY/i13dYBqsOj+N54XwFjMNlAnYXMfs5wdMLwazu0tSoyyFy/Kmr5DciNs0y0Cjl913CSQNJrJ3CnbUBHvPs2ga+YrhBdNiNII/1+yyPIb5gtaQfHNyjKfVMRsV0yGaYQmK4hh999Yui1R5688nnI5H984c5jMgAjVEQqZlfdanx5sf4FCmPJvBpIVzsqP045XHotpjoieHHc1MFuYei1A0NQKCG3EjC8hafXwpO0wv9Ku4QDVoZeW8vKJI4EchLHN9kmS+ZJqgm4pdz3PycD8AcrBtigEY8cfUPEahhgW+kadvsZem3rpyZpPtt3wbXC+iGYboVJp6Mz6B9hkzm+C47vtbNCgL/Q9FoztD/yCqPZjoBGLjS9Fr1bIwR3DRhv4tJrezvpWZhGyAjUpIXzV4T2jOi70vfTWpZee9wv8CSBuo2m8LJi6LVH4ojJJdKme8Whz+9NZd9o45VpWMQRtrRYeu0UFDJvIp4/nfDotWefWmzFSwnQc8IZNqaTkz3PsyZRAWMjDQBrbIggM6BnCcWuPepTjE1AmSfem0nJoPNyfkbaL2eO54yUpddCV6xBVuynpP76Kj0w2bQ5KnQRABv0s2+OXov6FEaQbYR4PJZeK8CHFPh+YXogcdStONnEUqPlpmGZytJrC4Z4WhrU/C/Ie96E3dFrBw7ut91Z8Fl6fbKKUY6M9C60NA6zLanN5cPE08LeJUuvPeoCsHZmuUpqfxrD0GuLoCPaUBLFEzLapNLUyQroCDgyq/9JsvRaOO2WNu/9KOeqKe7oEkZ7arOJfNMxenhjpk9WcMDkMu42QPuAMZps4WYrlge5TvD9MPTabIMToHZjgC1LrzU57eNLRJOn5ZuXlgZhNznZup0bsH5186hemwxT32O9B0hjZws9+2H2irFyU4zNcU5Gm14KOqKlfJSqyY+6J1Ij4qoVco3PMtawAQQqFcwJMfkf8c/JoL5xPEKGvuewk+mxa0fORrCZbxV/vzCg2LUo8QUGlb3tn4tpk02oP9i8qKawombYta2CIJcwZJzx5ce6ciaMLgUaJZpyiPom2bWSErgSttTxmMOj17ZpmmRQwPj0S9XnMHvOJfpk88P7OD023lh67ZFIgCFZTGY5/oCIPlk24TDwBUNamtD02tTxZDJhKbGOoO4nFFyfbEBGzdTFNuQYl12bT6UTwL8vkZcgzNYZFwigur7rEeOpaXYt7tNqfja9hQMthl1bUKcWJOFZw3EEy6498mTAvgHWwkWtRNhNSY1bFb9BL1+pz9fe8dpkp3ooaHMQRwi+baZNNmG1V8oHxihvA8a9b+xpKNADuxPcq0SbLIPSX6peDVF/7MaSa6uapDvmMFBkr/HPySTfA8n3vPaOj5zwyLV92J7uhhsctxLw940pcm1DJgunvR6Di1lyrRjSG9W65hbeq5lSoVtJSZX+0RBV/zGZPQ3EwGvQmi5bID/DJcm1x1eOpAeqSF2CJoX6nMtmve9mIv6RcIpynMuUsKlbuiP8n8bJSnMudZgxXu3XZvFgkkpxLo/9tz6eUefdLi0ISI0ujSk/cfOjUPeQu0r7ms6CSVZKZ+nanTtBfdLlAEhbT4n3iI+tJOkSNGfwViOj8K+AcU7WTTQOpWoJEgqlSJd9KGaXK5XPkQeZ0qTLNMF70lPXdgTYJaV9TZFUtLwQFJevqbPSmczJ0g3nJ89h9lNqeU+pL5xE8Z+LWenSoc6NgrLVAE2uHOkSIn5nSS3BlEh5X9PTkePePJEUPyi1qXFwr0NgjGDOoT7rEuZtrznHuyNa/Y+bkaHD/E4gUDpmfEqwfg3wHy1o/wIj2uOou/MbaHxT1gjnHMqyLnVOpN1mZA8uVHEYksqyLl9XNYrpN8JanZaourTLOiF1YkNlhGz+4cA0yqB1IqCu9Bbk38o7m05zNq1vJT/xzwqmUZYUtRuwJzmYkSnvbNoBmJCJWrDneOewjbJhvtSys7tUl3Y5zmsV6H5p3/Av+Q2zBSSoSYfLfagaPBdFsEVSViA6FIKClKNd4kw0enso4q8s7VJnxQRPTFnrwtHvwm66J2vsWDF9DD1s1WVddig2vOwaQKCb8cIweLIOeQTYuH4ou2oYMOyeAE923KtoYKZ4C1J9smq2LnLvngQ/H1VTY6tUgVh1iXpHyrMuV5ei1VFOiH/wUTp9smGoUMUNI1dXOfthtt0TpHdlxep9/1xUoVWxA8HbqZFonFKsSxskm6d5OLLVP2BsahQEO71Lj09vsk+GSr0NCEOVwBlIfdZlmdNkjOY1ugwKA0aErppZGoS0ItUY5W1NoYtQ4MUdo2yVszUdJnnSru6JOpwTpVmXqULqRAZ636vUHPGqMAStCoJWqzv7UPVZl/MUt7FhtQT4JyVtTU3y5NfsMg4Yi9sUee9ALRqeigzrMqPOKujxaJzmsKzLoiZuY17zU+5mO1HcP6LhL+HmEb9PZuMNI3NsvhiKdjlNwz+dRUF1t5/QKnTFzC7fTWWJH3O7qU0vB/IIPazRWdrlOXA7Dh+Y7URMRKVZl2mduA0H70eT+SGm1ybraJPJNIOOsg+zP767cXdP1qWf47GsyzQg8wX2F5LaHD/mrqIGabVYY2uGFzXLuswTyXeB9LyO+zT9t5YhWZdzCPpjIjuzBnVZl2bqJalb7/vbHFV+w2zRwN3UvvuJiFEqYIz7xkUN9o4ZLLj5BMO6LAkI/wb8VwRaVpp1qSaPkM3tY96/cw3C7tRiO9Ri292swdk7XpdMjCx/2nLEwxKKdYm0RPL6+HoK5xEs61LgNltMzy/FDVGGddmTqX2jdTLCalDYLhn6Yi8+2fp+ksYnGutquqIe528/y6zk39OeNlm2gvoy0oofjSFdmsNHBtkrxbuPbZIpyCrGrM2bRI9oktW2+m0FBpC5BuQi5UmX1nsqBUYstWxSMrJL1gc8isGdT4EEtLqsyz5HNl+O+iEt6dwCDOvS+LV1bZQQ5qa8q2mFwRy+xfc8K3jMXfaNBkwpfTyNLh8CchL+zST8x2XWIMG1QOPJ0PtGHdx6fCl4fbLeTBhh9KtPJsl/6U5BEtobkjA0HLWxxEtjXJ7OFzOHXR6GeFlKMas9ORc7+3ulsyOtceKBUcDNQLdCWeLlgCNpy7DkyuF8wuNddmuFarekud/EG5ww20YZZAxLvW6WIFskG2UZfZPjvNWPSVEQdbfSEDwrcNEM5ZqV5l2KIJFX3DFAzFQi7IZMbWbAi8UyNGwHe7xLu+lflZZeDuTVv/KZRhmQZIIUdJRw9MTyLhVQtyNbfivGqqO5qxTvsiK1K+CiZ/mSB3oIyOxpM8w+vVhGCeDVyvIuJ+T3G4Q2hoQr7dqaKtwapIEWm+OsjLI1NYIfkNWjBNrASvMu82g3D2k0vyV+zF33BLbwFRRjjRi2yvMujRtSMtpQKX0NbsUJuxOiQ59ML0/J4FG9Plmyi1pwUUvcGqR4l0i8bUg94vkBzbsEZ64MaO6OHn/XTJ8M2VhN8+qTbQJSGv7NNPybXHVCde9plnaZUWlB3LbFszePdlnPJGxo+oGTlecw+5p6vmvqEZcFLO3SGk/nDswSVgmUqylUqktF3RtffiztMlXcK2Kw5XU8TyLsZnSJlAdmMX1+lP4/MbOr7J5N2R0MjB5/MFSfzD4aiFTneE+TfbIEvlfBkauSw7YWxboEdbO095hD4sdk9nSBorvgqEQq4FFZlGZdQpS9wz9ztHDE47EuR7Ih9cBFX+PGDsW6FDN1AZBsxjcqiyaD0FKB7LfmHKbKDOuy48o/NuGFBk7+5iNZlxWF0JHuwXhc8k1x8OGeJvtkWaBDV9sJBg5+UZd1CexAMpGy3OJvm2JdQrcf3i49hf07lnWppg+Ice1bMDb5UXe5dx6mbiM7dRulWZclgw1Tav6sp8vzSrNtsoVDMAvR1uOP0vM0NaHYNMxHa3OKNapzYnYAc+fAojTrUiYq3nrTMWr+d020yXRCCx957aZNpiyY7PLjMPfxTSlDS/jXN6KnzbDx6JIuO5ZF5uIHygYTS5EuM65+GMTMuPfNki7VsMANsGq9c1b1OerW/dDca3E+bEoXskd29mEK5L7zh6zkwz3NipMJSHgQtO8aTqI81mXr6GiJjTDLjPcgw7osprRQLoxyiZ+LwhhB56tBKb7p18rIb9QtFrgZj1OJgprV8E/AGB27G8ruET9NWdalJEBiOz6dPuJCYboeLAYRrQYXiZeaoV3+kjmEChhrniD7zsM0oeLsm1EnQ5ZXc3lEnjwEpG5q5PKlAgY1263pGIWNb2o4zzQkpL2GlatLuxTzosaRKBInyxTt0opz7O0fKrW4AWP32mbuteMy5ti87daoGKT5Wi99BH9T07RLZE/6cmL7yMl0E3aTkwn0vvXyDg0e1RPxz4ZtM4V36eGFz3iaOj7Fug0YO10CWgOzJs1x6sh4mnZoa5x1VgyFoj1NG2DKApNBEIFL/JzMnoZMJ9qPPXvJVPvnFHmamldasSF18lb6HWYvjwAN/3Zl348V0U/AcE+nNe8tLUGI1dXwf0fd7ek2x5vG6Wff74BU9o2KOg2Q5tXd019hN6QdkC7R7+iuVSNiqje3hHGW2lQrT69ce4fZzjjQTK9raw/Xp+knYJx9o3eCI1d9FYd31L08Qn3LI2jzjsR3QCYlgzjJUfEjJWsuGP8r7GbGsZa4Gfp7eOkoYrqeplCtUEFGpm7y/Q6z9+VIb1+O3ryhyU/AeMaxDtky0CUr4mER3lF3/VDgdo7KqIX90HdAapoFDEIxqY7ePYPvr7CbfmiB/Nw6LIeryI6Yrgqdocn0pGl5jcZ3mK06wrAmen0S6PADhnsaMOrSMc0q4uFO31F397RCm0zhaVq9ZP4dkEKdmNMlzKMxFG7xz0khjNZDdoh2dDcdRdDqtb6hX6fD9CDv85f0HGZvSY1xFrDKIz5o2YYotBYK+AhoP5X4MbcA/5V+ViBtcvZInO+AzDirYFO/ttClWCUpflBiVyOBOvK9S4du+p+lZ9eQT868qUDPG6NInsNsSZfF6LVX86RRAcPsG5osNmfUq8cTvO1WHqFCW1JnSK99B6QqaqPtAIqRIWfg3zMkvdZwJ0ZzL/HB68EGC7rdL/wqdEric4xBDRqwGFqGlzSwPq80K0PXgfAH+Usv5FzwtlvUoN3Ub7O0IBdlTU2lmSe1SZ+U25QjCrvJyRLGG+hRiIdwQEyvITqaiduU+Ygwkt8wex2M/NbB6N3z2fsJGFPxTjIsaKuuCu076h/T8Ne4eGHptfl0+Mr5ovYPf+OQqEGwlFrFRV3iema6WDIgkxugftfwV/0we6NiKNqNa6La4ufi9vS47emU4oqa6YfCtb0qfjmN9zRNrwVTUAb6oUXuF3UUd0PFg4cd3JqbhqWHx6+tE+quAikRkRxeWBS/thi/duV3vYbHN8uvLX09WZUyftQ5ncfcAk8AEIU6m98QfQekFKtQGKikd5vMP9JYeu2HNtmQr039ee669FrgiY9a347x4ZG832H2pEuU1KtWbXE3hnY1NSFf8Mn0krxW/233EKOElZ7f8P70/JgUl6Pg+IYqFJTu6tOI9SvsJvmGWwNE+Hv2UMuI6arQocJQUBClxJ1Ghl7bOvRioYt0Cc47XzWrQgcNtVIw5EgSLwzj1gBr8Iq1ycXD4r0DUqampopwGnTU/c/JOWilt4PWR53+8JN6uEHczUcGj6XGFNS/BSjcYM1v+/FLF0m3AWPkSUGdZTra6iGX3lG3JbV5sNTLaN7PyWhX0wI9u1JnvpjUftnKupoCWdzm6iD1HF+IHr92msx3Gu+LOrgBOX4tWJew4GxxAsG6NQBZXJPZj9c4n2DcGmC1XqFQlkt8y5B9smxsyzzgJ5HumGUNwu78axPAW5c0WfUPiurtaZtNV1TWPvr5HWY7ozbtK71QEiV+LgYhCqJgwfAOU44ZP+bWgQVCPg1WUvGQiOXXHokPju8GPp5mTwfjK+zOKw2+HDgl7xfiw9fTXMoleieAaUnd3IBMlwyDLIG83cdzxQHDKQfUG8qEaMwqNfyJIEWvLejzQwczxwMyll6rBRCjDL84zLOmf6KRuMEJNwT0O3z/C8T0cIPWJZMOQqyK5y7wDrPFDUI8q+b23SXTMGB4T6MTU+AAoXns33YrDLyGMcdTyl0YOPkBKf9DMf9DEOVzCbt5LLfWumQw5P4QlnxYIqdLVhMcWMxPAueD3w+luLVq4inwP3QloH8Cxvf0Or1ruuE5avyYWzSCma+hMNpkZCy3tqNnYuM3WLr5nSOWW9vXHdjgh9S/Ee9fZdZ0ZxzWJetvNEKQ6lDcWni61NrukmnOSrPcWkxySoPe7tX5zn7ULYtagW/o5dtVyQlI8fCAMEodaksYJ6T492S6ZFbH5BRigVdMj1xb7axN0+xrkyfk9w6zb4gCIApfxhEuNUuuVcDSSx/pUqHr7lJTpqYG8G9vLLB/H7Dk2lrM9imjljYzg/hBKTSZAE3W71nu8+fjsmttjqrZsu/queK9w2znWQU5GaqCFuZkLLv2SGcb8AjtkoD2NyHDrq0AsRxJVLurfQePyZzf0KtUhTQgJKD7x0TmOewO4V9hdbnee8gtIX14eXWhJ9WgJ2+3nebeAxS9FnIDR6HVTjJo8BuSfbKMhrrRqYzW6X+RjAxdgwwGegoaT71Zeq00QIu13VyBrpMyB3F3yMEJ5GA7sx+/c+TxayuURETktCL9eKyfpWb6ZMUYWhBPy2GfjHY1Rd1WSpkXHiE4b5k+GfLQal3gFGZlrKtpwVH26tWXS6x6fuTgz2E35zfyb6iSNo03j9cnS9Mk/CEeV+KamuHXdpDRBSV/n55i3E/AWJ0M2TKEr2XclYHy82NutSWB8Ie++yYrY/m19phq5hf4IuuHXfFz2I3iCUaXMMHqm6/c65PhRV/SwBI7Fb/DbFmX1WRy6pOrqbgBY9w3ThuzpkoxnEypPtlEUmZO4bfPRp4DMistazFUTizUmT8V/zmZgRbqDVDergvROSU9fm0yLofp7qcYf0i6muIiWFv76n2L/1wUmqxDW1LQh5ohIpZyNbUNZwOtuKam+bWGSz92Tru8s8eTf9hX2I2wu2BPQ4E3hxgjj187VM2/Vuo1pPbBOwy/tsGowNQRWtz7Zvm1JcGZIsHu4qPWcN52y88C4wsTsixxjtfZmhqe1LZxTM+pEHF3VDxoimT9puI9xPQaZQPMiyOBStdFvQmzbZRBHgFa1+3b5VrcgHGjzMRtTBBKLdURP+oeeQIi0Gpm5RihTfJrj02tOL7VRpjn6LI8b2q2UQaLk7mS3FHCJqFHr62W3SQrjtbqTP+NKVdTAAcBHRh6y+YlDBhT8VZbohS0W+cIO7cMvbZBg73iat1A/Fl67YuujJIaYnmrDzD8kojtk60CvRX4zc/wmMw+mgyjy9MVr4TJN0WvNYuPDG3TuH/H0msLvNYrenCa0z7q7vgeBi8eHxDRZ+AOTa8dBgbuAAP3FkJESXrttEoapgg9zik8eu1RpE2DiOrVJvMhQQy9tgF0ccIRYuwlTa/tK5st1QrWEd6rDL22ZuQQwzxdwikRSa/NivngSzOvXkPqFj8nJViVIFhV7j5VT4/q29fWYq2TBCqeRKgG0r4WzKfjYpin/aFXv9D2tS9yKCaMKw2FP47Eb7tNycTkctJdQjR4b4peiyZ6Gt0kym6powZhN3CE1e1oBh8sAW4wcK81jcajZMuX3KCXLJLutcP07KTf+VnpeU2UXGlU6RnVlsF4nYaMkvTabO7j9eyHir8kSq50macI3Xx7922WhemdwKG4j3pfameNvH7oMDyCQvmkpPjjZvqhvRvaVM6UTKmA4VIjgcpmoT1mfIRR/VCB104e96UOAjIDrWoqdNmM5lFxOjc1bV87KpIxM8jpQZEZ2ddC21Vqf8PJsoNVIu1rs9F21qU6UvwJsg1R4MiK1S+6OW4Z4CAGJhVpfY74yX/AvtbG0wKDXSPNJ//6KiwiAXn3uJyKgzvWc+Zow5zm0T/QGmTxpH1twVcDiYnegwqGtq+V413XD9bQqr92dRB1s9QDykjH/luzy+kZkL0Dcn2yZH2ycs1Y55Ov0lfYzTwLCv5SLls8cfAsvn1tMyUxgZL09vxmjDkMbgoyx9D4pG3s+Q1SVsOkdW72IGVfi3NwmIpKUHbQ9rU5DUynNcFmt9ZgIsrb1+JWaMBqtxbgvn372mG5ck7IaLPEe5qyr0VShs0S4iR4+9qE7VGgqozed5DqMchBCO+ZmGiWoB78I/a1sF6pVmi16dk1fYXd4RFgZwNuX59BTe3719aC49tk3rb5N0OwtclJedNBg4OW64jKKMDMwxQI9Uxw9jCKg2AhHidQvt/Uzk4Z7FJjTlShMAJCtWyWhWl+g6ec0T5JATjfN7AdmDsduxqAsiLBnIMzsDUTSSnvZLH69wrZEk0D0BO8rIYjVs7AtgJzWSaw2iPOHdmWaMIkSyHdqH1TJ7AtUUE1nS+1ZT8n8wi2vVoxbQytXMOKgyHYdviOGx6hjUCdjDawPXJHpE6AlSEn8xeGIdhW0FXLWJd01vBCYAm2FfbRWsF6hqXyiFeF0gZeVzRsOXv2THIQ02uJNgOHTswuJd7TwiEHrWbTc6CVnZEO71+bGuoCNbbECCt1hmBbG7RswQ/JEn86tOIg2kUG2cK9neNVYU5vMYzR2HdPPIKtUdFeGH/9GHOoH2Y/uhy30WWO9zTbKCvrLa/su4X5BEOwzZC1KaDvaA0Itrx/rUDoUxV8YL10odR/e6ZPBo2g8a6z/Ozb49fWjA5RmqcTS/wTUrhBNE8ypC9n/FWTfbKJfl4Ray7HCSjDr62wwi0T0HQNeDt/wL9W7J4GHRhsye5fhvmf/gEq9agBM9Y3sO1i9uOGksjieXu9w/wxp/kRSA7SBrbHpoYnDk5xmTM+vhkhurJmeBWygBrRWGgD23wU/gY5WdUy4FY1/jkZISMgTzp+0RKwJjQg2OKsfRVcH5ta/TD75sl4N096D4sC3sAWFtJmszNa2DyhDGxNghZGNh86dPockNrU+G4UZrF6NS/L4zyGJNjOAfF+IN9G/bJf+3pU15hDDXnSDRgUYBpJ/1qDfddyUbSG2/xlCbYJzMNiPeX0rfopv1F3FXU2JQyQOSTe06wMnVSjeuPUqe2WfEsQdgMcxE855nV6N/9Ru7fS5142LyQJhyWUeW02jw+QdXPY+iYJtkdtYB1qwCdm3T/mLiWDim8pUCdp8dHDtsnMXNdcPyCPcE05chB346sENDCUA0LUpO9ee/zbyeqscunQFX8PMm2yjN+tvhXng6Vm22TISnLHlGNq3D9g2mQdYnZgKu3qLLJNlvBFvqjf42rndf82JIGDs+OnXFnKpQ3sLJEHHBz9hIj2i7UTfNwMw9Y2NUykZoqbMZNtiIK8OED5njVeGIZhmyokq96AhCBzJLtkOUHVJsMiVnsN4Jy0e+3Atd8K4N81rDxcgm0zLjVyCSiS+o/GEGxbNS4HcMA9QNnS7rXHkQMTc3QvbefEb7vtkg24pJbYbOcdkOmdQFdDxUDLeQTqUrx7LSx8GnAtl672c0rm8msFcDJF8fepeSLPYbZDDvPaWQfYpeyu3yapPwHDPQ11xeNyrbAIileagZOhGjxBRjXM5mn32mwIf9icvCeXwc9JrTTaY/gj7hu59NovNEJJYRLK0Gt7xkrXtzKwPwol6bUyIXZSMHXDXknxY25dlXB+oXmUNRwms/RahXnf8RnZBPM7nxAn7AaNAMUqpCebaZbHrj0OBIg1NHiQ5xK2dRh2bbcWa4Ey8LdLuLgBY9zJ6knkBshpa+E9zbBrK1qrZb5d8fxeDMuuTcCdnqJ5uKdn/HNSbg2CH3bVrP2rSP+K6YHJoKEpMgz+fad56XOYvatSersqXU5Xug0Y7umKWzXh3E4lPimYJhnENKvVb/kLIiq/Aak9DdxJBj0SYDI/92bZtbOOt11Vj8fzrnstmE5HQW3knRx/hAy7Flo+x0VQ7p6m6j8X1STLgA2eeyZe6crc0wWwb70A/jl+b2rG0U19DiRO6Mn481CWXtvAFBjrhPywYMGO/IjpydDlbmydZFYs4TiLodd2a8dAn2tInDyRYLIx0EqexpXIIZqFtK8db/tarYGnC21fm8s8xRswxkspkMvj7WsV52PT+W0z+HBMdldEFPJzCZXvh5GUPIfZMvHQnYb9w6i3XszDuciCyQBbKgK7otRDlB9Fr8UJe2zqDwcWfV5p1r52gIBfhikDz1t7WYKwcUqWwS2GKWmvIW7Cda+FkN9xUec3E8+ff1LutdnEydYJ9tHSSWHAcE83TLMG3lN7fFIw7FprqoIkot+9GPkNyBGpkUiAdYGpW/u4GZ7DbvZ0RX0F87ko+c6+/eGEXrMOAxhJUK1ljp8lhhpc5d9VFDydNZm2P0yoNEpOn60T8R9zl5IJUjKVi0ftsXYyy8/KL3gMrgYAjEcOBvSZ5WdNLHEDcT40usw+PwuGOPLKwi/QYInD7A1Y6s2AJX1NzsUNGIMGBaBBaNAkDXBQmeJnfZVZLd4oLD/LFGOOx01vpwGPyZFpfhburlag1tnjNfJwJyo2uARBIEV80Mzxsxp+tzz02+0phwHDpe7TlvpNpM6OOlDm+Fkw76sQAPlxVZLfgBQVr1k/tLSLXuuhYzNNz4JHY4OVa8vBjCO79KwKQ92XOIJe2jbF/7gZ2IlVF9BBrCMYj2WengUR+5KRJRcJ2peZo2elBqe0Bd0LEUaZp2eZM2MCfAkjOM+/LrPsrAEVw4YTraX4+HZhJ0akruZpWm9dMifMvqJub0+8C0uWtwE3F/XERQ2rnbp/262C/2rV1gTuYQQiz7T9YUZD5sjsR78Ig+flVYKwOyYHvKjx5Qz9mkN9nT8e7qQj6xbzP5ASb2rK/rAaU7ff6VnOZ81W1MBR5Ymllh6nUIywOz7yUuqlgxF8kWxF3Sqs3EzKH5Ag/0gjK2rAv8xIZNSg6ZFdelYFJOY4vvXTP0v8MNucDIPLip5Ovv2EOQwYNkRhxFnOOiYHVWWm6FkV+iFlQmx/xB8kWVHnhkK1JPR4Sg/aeZm3P1wdmeO0nOfeCVZ6eINL0EpVzy5m/GiMXhUcigVC4j19/YTiBgz3tICd1XFGpBF/kAzspFrrG1zOGrSeMs/Oyt3GWBA8SyPe02RFjd5J6++KOqgxp4satD0NMEKaAT40c/aHuRhj/keELg4YM+ahugPxfs2RV3imyFkN2lynrN2ML2oSdnIsMJ4PFhCoqKe/0iQ5q0J3F7VmKCGafffDcZoplfdK38EI+htmDyWbbyjZ+N4s4gaMK2o4uWSjJ5cwJaPIWalAUxq9kxp+OjQ5y8wkaqr90quSRMT9I3KDJaz+fftDyGAcDweo3+Y3pGSMmkFYdGfWl1l2lkzIdBxp3rh4eMW9rBh2VkZeV0q7QN/FzfFY+0Mx+8MjNuZud6NLfX57pk0GhNFEbVTDY9JjZ/VqTN96kybzb0DS/rC+7Q9bDZsSrP1hautOKBgQxT7FmWJn9b6aEDV/8vCC96bMGsxhwNhZ8xI82cXdwQY7YIPz9OUIdqNrfyjoiFZMLnPfh9kvNeAISe8ME90GDJcaSmcFjRmU1H7qyNCzCjyuTENUazDPyjQ9KyejhLY8r2nMdEAimadnIXHskFEZJT7RPHpWMnrW2UUp8ZXF9MkARJCcLxVyiZ+LSr9Bne7AGE2NbysGeTLW36qoEnLZB2QwRg3jDRm4qrXHCVRh4QgYc3T9lqF7iPncJ0vOf+T3X94qIqi5Hn5g25zbpLIDSwCAbOSbclj3MqSsVkENQO8gy/69OZ68pYroePf8deR4YTcOaVCpSvWDj+58M+3/z/oyLTE1djzMO2cAJM4sFUsG/CNyx+Cl9zh5YFpio5abNKzEG41siR31pLH3UeaPfnPfdH5OZv92NJIlfXsdPvyi/Q+t78O/vJ1YATIMAaAR6W9k3uEwYTUy6JRzBsj4TDocriAVRIMPd2h9DvgPzDFSDggRmeZfQV2+DbhaSXwiMh0s2Dod2dLcmeBkmjg1BTcHjDdl5vhi5hTX080wY8ZZItnBKtO60hPEqVbiT4mUF0L914DN6jVAH2aPOEUesZTOOgZ9uEV6JGGWabpUh/RBbugcpxZvbEpUSGBdNsodsln8gEzfCoMBzaDHQ6Cjx29P8ZoBwy55jwRx6FLcEUu5ECbz3nvz6f27iSVJjQFHTaA1JLSbzpwLIXoXBZ2WUAou0y6EpcOvrGB0AymhSYTdmRDCpRVjxBEvEaMBNIHVLPVS6xP322bZTROeSXkaPl4CT6tMsZuO9GbCj3CcNOTNezNdpgI+wJHoocsk8afEimWDcA5Xhp7DLjdHSzK0c053obDnDhvr+pdmB7SmvSd2/i3I0JIGjKhqXh/Uh+m285iU9HGy9hC6+7N/mSh6YTenZDX1h2s2K+7JS7n1TWgg3S6y6vZqWT7RAGU6jxtzuvqvzrR1AK8pkDbfICVYPpEm01cykK2cS/RuAz+H3aCfoG4KFYie46uDIQKZwmlB82CGCS9LBOrQGDZZO7Sp/XyKIQJlzPBKxaQ6Hq+yRKA8mzn2oh0zy20XaRB203lLq6fQpepOqDuzFJ4b4GikEN5BU3gK0P7IsDTHrQqGwtNrR0mW8rf6iTw/JlOSWb4vmDFjCufPMVkGz6zlzYLr+aul8vXuTFcER5zAdLinm3DOw0M2Fj4CK4xkVfMIe7gM9aaYqW2DRF08qWepN8bn0Vf760rZg5SusQ1suBfCJzj0O8scacZ83pE3fGgmaBgwXCNQy0pCBiYaH3VMZwMY5oruUm7xUdfpedKweVJ9M+H84QXLmukYHSrgzZtEkWltVHQAYffTMh0wvI4w9codncsZjyYZuotCbbQUpGHz66iT34DMPqpQBc3Wheop/uTJ1gY6ZHVCeKSFAxzGBa4bwqCun6Df5535N61hxVwmDuEJFF4f8aszqBo4qlew2XKLE3lWzKVAbS1PaT9W0RKE3ZRGkEdNq5HSNKxkKPu2isk5qoPewoQhsyosOJcKAORQpS5uJcPYtxnZtxjz/tunSH4DUsJ4E64C06S5PggmzuszTdyGJi6UmmbYPaOM1yamHGV1R/sIv0/WeC3BgatYb0F72BBgjNdax/copZ3byOdlscZr54qXjqQOGM/PUeFz3F3KAFCQroI3dEMqJCfPeLYwiIm0vwrPyRugrGYc8zXiaReKk9ekyxvqr9GhVGhOXrfLzbybstHUncUvNCkvAVcGFG4bwbS6cGw6U26s6wF6lCQX2u1s5nW0l2QUqxwMXQvFpmumHZMAKJDgTC4sm+5liAx4kDa0LlKgDVlYMt1oGfI0UMaQALVeOBYcIomuC67X+MdkdWUwAcpQkUerrsSPuW14FzS807iLOr4znJ+AzDYyay0z2jS3P684LCwNbg7Ae1K6ZgjV/0kpRRhrMqxi7sNzSsKAMQQL1ZEa7DziaRSOvwbFOwO95s0RzzWCXgqr2byn1tk5SiAeUWh3sZZgFdEuUlPw7ozeMfqUJ8pZv4Ca4gaM54IrX8rQNJERQacKRzyrw6A18uTK+xCQ2EZtANXdMhKRnOIDlOwDIVoDAmNoUBwVjjCmIPFnmJikeFuyfSBIy5dk6LHIoahQhLEGZ7kK4mtuAYin0ISxirxGa51v42TJ/tKThl49wTxC0x3t4Lw80weqRgBq856B5Ic6pvBUryyojsCP1HqTqnAec+vEtQ7hmnHSjUCMrbBUr6LIZHMCNSab6r6/RmQfaCzUSINSYKtxnsz0gZqYLXXfUYrKH7DQwgxumJlkij8lhqSVYfmU+gdJy9lHZB+od+yjZq3vNm4G5BqE3dxGoFEDutZHIG1QOHZVgeMODJFGCYD0hWdXQde2ZGSdSeKFZ/pAA8W6+ZFuktlJJgwwY1NTGMkSWs8Wll41JjIGs66I5HgLx4uCNNtRG+XvLPE3Y6B5UQ1tGzWn5bh+ZXhRGRLbpb5185NbxJC8qKJIQ3LCd4qd2h0jp0KbVmXzlaw/5lAPj8r0gZplDDPv8NKF5zN1UB/gsmHqie42YvhMDbfledLFySzLZ+qA3R17FJqb+CU8Lnz5A4QmAaFJd0PywjGRarOMod9TkLwNuOnVwbvTmEhx8skwkY6PElkdRJRL0PwrNBNpNAzJe4PcOpa+uBkDaxSVYEqAmVyXAMNaOArRBEcKGghDAkBw4R2eQEousNORPuLPnlHaKRWtutHOCWxxet6FphANgwP1uu6PDKdC8T/RzGZ1SLlrOokl3X95CmwCWDGMUUcPU1phewwY9BRsTgBb/YSW4f4UAOBKT/V7LuG8N3MdwfX25fyggHDdsroo7IYbApX5pP0cwPrZDeWplBume+v4mBK2Z2lPpQHsQkYDaPawx0DRdxTMhFTzmXgn/9NkewwJojbHrYTEu8Udb9ZUaZqV6bwwW93/6pkmAxpAkmGcWW8F7MNDshQcQHEz5F7Nxdf/6pkmA7zdKqARH7A6eX5vJmWQZu1UtH0rjEU+sOfPcXegLfARMUDrLWyxcDwaNOtQvrca3xyd7XmjgjUkQ5f4uye6DAoxhlKS3JXfnI+T7DJIsrFEzhgdtZuMdRR2M5YQOLuvsrie8erzuzNNhg/z5lChpvA8GmCAjpThrQQTfElEk6F3TPcw3ckzkIAtNI9mZqOwwZ4NVEVRB+NeaCLNQAcI3rn9TjLJvzEZLkwxd4N6Aeuyo7VdWC7MkSMAypBBZJ8t3pwMF0aQKMK5+8f5TX4DMmndFDRS+5yXH1i5GWQmJ2x8HeEEtQO018A1onCePyZhpvNy7B4fxoFewLhXt3gFecA1KcVJGEVnyetQMsu2nPcBmZ73BBfZtFKBgzuZUDUIu3HGBhQZEJbWwp4ARWcxq7Us/Tw6/QKWprN8nHSA3fhNBobO0jBurynVO2PwuYYj6SwloYd8XHQ4P6Xf9XGiuBsZ6dVXbLBG7xHus1B8lmZK3xkBc+DyXHibnY4BrNxOuuKvESN3UlZeUwEhvfx6g/emGkHFWt2w2TGXKrfnTfvsGOeofyjbOFue0imxJgOwj5sPlAYydAMy1MtGuvg/aaZuo4LbSO7VUXnMvElCSxEAsV+yvvIeHam/RmSTAb2LBtO0lsMKVin/ZxMoaERDlba2wZGUJ9LOTUOVYrSgX1GAqszx2J1ltIwT3o0JAs667vanWWsbZJ6tdfmW3Hp4d4bQAusPc5jsNZC6Lyyh5bh/MDpKGM3IZokY42bogBeArHL7GkvIb0DmOrLpnpkbmMlmcpsMNKMF3QX55O45L8+YySQoFQCnNyScRfGMFhxMcMSGaE+QhDFNBsAJaxLd97xZRsucKIpGRRKKfqr6Jz2JZKjWrIPBX4/XiBGthR7c6cEoYT+VZbQMKLjl0d5T8hY/5q6fOiEE0cETGrfMU58DMv1U+DHkBHUcg0Yl/6xjVWs7HATaZawa5EtMk0Hwrev62OsI0VC0gUvGgMO0lnqPb01GrCNBzKHJhX0MNuZg+0AgF06IfeFykuGfoaxaB1RIE2jPLb46GShDMm+PtYVGihMwtsmAhT+uOvB/RwhYYygtdazss0A/IJe4QiCbDC1bBYszz0zHhYi7QW3BIw3uFK2EM1iK0wIyseR5EZWFChim3nBiyagT4E3pI+cZTktHFl+hEnyhtpL/mMx9BPkzHRlS7OMuxR6F3VSwEM2o80Lie79opdgSzRBBoES2GihrV5YtIR24+VxReX0U2s5j7jPv9s68NVqiSrMlKpA2R+kF0NaH0aIEYXdGsRVGse1bbO3hUSkkg8mzrsu9S8A6qjRZoheI6KEVgmPPu40qRZbIQH6V0uRpifQ3IHMbtWJiGRgdzUjsoNLOQyg328BwYsafJ9NjyCs9FCAtWom3JauF2iDqn40YNvaPuU3qoJQy0sU58gZHlSdLTDPqxNWuVzP5qTSsNFei4aAbGMVFXj+V8/oBQMAEzJsEiIPKciVkJqDf8LsCVtf8r5NoMVS1NlBNT65ODwGpASxYyg2mjopS0+PJVJYs8aL7N9D9+30Yl5/fnkEy1IQuYtM79tH5kmjVDHi9q5FgI0+BSrEligI4bm4rLT47K1scFcM+wpbi8nmom7CbHkNHj0Ev5nf1P3umx2BHXYVJ9nc7VdyAsRAaoO2QM4dqhvpLxKhmJGhHm01KZC5XabZEw+Fx5N2oszHmrPGDMoCgtfItrSSwbpIbBscA4LRgo7dodFRZtoSmBHql6diXe7Kkz1F3GQMMzUoxp7T41iRVMzp6Cy8SNK6jfmIf8ybuVpsb0ibS7xqrzp6nFEHVFILkbj7uXB0skqEYpWUB/AFbU/83ZZAMBZoMat2LOJ1lmwwVs9zZUL7NH9SWOHE3AFWzbBx9x1mtFF+iQfnQvMQ+hM81DLjxHWpv3yGDFvo/KdFk6IDnVbOVjMTQKu1G8wX0BnvPU3GqtBsN5KJNSWFEjqeVoku0PEybPp0cWD+vo+kSsLEoGQViSCWvFF2iJwGlZf5oH/+m3qyNTDvPOsiMoysk6nigVdpGZuI+ythGKcB5V87/BbNNKWuphoQJGM2XQIOlwPJVQwWFSvEl6qg2O9K70lby35tZo4b+cZNRrl5dd28OYWUzcHd24DU/WEK/JxPDlzAUpaDD0vutkpEwYKghDvXUktELk/g6opxboCRZ8TvmuBnC8iW6WVk3KCpq03t99JvW0s4t4J6Y6WgK8zqGL9FRdxxrrnd5tbwNuDnrgMWHiHPN4XXE8CU60MMVt1Lu8aKzUIaMvHNWGFIheZof0qzPcTetIHDDOoBwLbA7rpxXisLfGCZAXYOGf6W9UjrYFxndMOkSX5uMV0ofkLhF0alhn4H1ShlNjdMCyDOqOXVzBpYw0dFYgURQH2GPmvI76bXdLGJzYOZaeb+TgRx+Qj3hxyfm4TG3WlvNlKLLXX4mPd/tLJahGENmGNzkg02egribNQKsDBaLdX7V218vzxAm0KSUAjyMhA1AkjChx6W58jqBUvjscc5A9RkwNYD8TuhZUmnCxEQrSEc2b/dxyxmisLsSdqBd95ZxUv+zZ/oM0AIT6LtceBPn5dk+A0Z6px5ajTRpK8WXKGWCGybp7gulfkBqMgEkzFHIdMy67O3bc8pAQhkazN6AIl+fVvd/UUqc0ygtpkH9ofoYBQyvo4ETqSMdmTlsgFJ8CbBOKlSdc41LDtY5F2YIR0qDfVlqvI1YUQaAiOd6+VHCgRRFl/hwZ2qb6miyjaB1xJWEtLPHY0iGLpGLuTNJ+gY/OgGZJYI9nVYg18yaN/iWSCQDhj0NWKtrevSc1VF8CUAjjowhnfAVPwXRRHdUCzqqFVrM4aXJ8CWOEw7NOtG7xu3zp0TyJUrC4Pm4hXDHYbRbHFWGSvt/2D6Cs9QGI8AQJnoBvBmu8FfGoNuAMQ22gnZkDdUeNgUYwkRFxXHsz7avYFn/j2EWQabnrqN9vb04YXf91AE+l5w9geFuTY4vYVAGlRM4Lh/IQi/gRtsEqvjoIs8WdtIZvkSBKEPpAB+0eIlIKMOrBQhAHdzhy4gAqpXmS2BceBx1l7df87cR02RIKAnM6SiHpSZtAAKplAx2Awblm6jbQTn8UQF5zXGWSPMlUBTpBPo1o/tf3YSJ5EtMoL8aMA39TEGeB7sUXwLVu2Dac3m6P88llBVlyOYuUT6FH51bs1D7qL73Uc5hk4HlS5gqulYD2LUSgYgrTZjAFLL1fIkEBR8o02SAgKZAhLfVwEin8oSJCdMP+JQAy6B+ysA0GTrI5ABP5xqvEanKMAcssEfBfgdLznPjqixhQhJAvx0sBOi4+Q/LdBmm2botgkef4QiaZUx0KM1nfEryIbPmPOY+ZyhfOYOPZmAZEwN9gFftNd+q6/4UgWVMfPqVt5uF0kNMhjEh4M9jqjtKAO+vvAdIS+bTUj7Adc4aMWgGvHdpb1aL+AkYiWaYSBZ0wBIc+EcRf43INgMMAWze8THXfnj5Qa0ROkEr8VyXU/NfnmVMQNo3D3SZZgyMoRgTkNAsbVyJXVBz0PamkBsqExcncOlBMsLKMsC9APVW3zwrZQKCyg34+WtkWJ/XiGVM5AFwHYimScPODWUCAtuwasaLNT6SWcZEAXKrwdnPZIJ6/KBM0gCWZbeBefjyFGNioF1XPguk5w+JZkzo2aKcV/Lt7yOGMVGNEzgx5ZhhJ5lmTJiA6BDF/H1+SV96YTfEI/M5AriuBzqVlTQBMdxWudoMyX93FsyAjmoxZReZYUeVMwEZGMJWYlDOmoBM84UeGZLJvdykM6KwG0wQJFRhg9ujoUwjSS13rPcPnVzcgHHTG5VmX1tThtx68/r8mNvZkeI2krnjwTaW1FIEN7FOmMGDBzucOWRjSS0vmxbMs/Wyg/C8SxtnAYKhkdRS7/w95+VZVgskXjNcQWPpjEaxWirgRWZ9nCNwROMtQND80QHjbIwnXA3VxtJajvLIwN7z0jep/sozvJZiGjSr0PxQrXt4e1Y7A05X2c6SNANZ60bxWlptJo0/n1KGh/dmyqNifBb8CYmX6Z9LZCvIiORljnuT2vlFGX1OaNocx/zl1+uVHY3mtXTYQ5pmnYoEyWejeC0dognngC+Shmo8r8V4N/3MGNYzegScRpuAYPra07jEsbq/7kwraAzrMpSd0EOjTUAG4JkZU5m3eXzyo251bhPsjpAuaiBU2GgTkFHQnuwFpn45BylDo2ktMBU2kEhvga9dI01AqnXr8s6xovEmINCiKGCJQW0rWPjGbCNkxeZANuPMhoWbQNf5OEgSeunzHPA9wR8bS2t50cME9LD8NJD7Ckq5gNw9EtvmMmb1ORvcvVo30+L4syc6QQ3DwmrkwBLnsyzepKNnMY0qtVqq09HSbCyt5YiGM27t9tGD0VnjWC1Q9BFITV3wx7wNGENUQebC2BBd7+ovEdEIOrL4DvcC/ZZQleeAzGTi9LtWpN5JI4eJxruAdJRHa+sPiZMwBnDyKctQ4/yLls5Aa00M6l3j1JtpBKHSqiCv5hqAGRrvAtJMyqkb8FXORpBzd8x/JGWIS1iK1gKKoQDT8CFvksOAm/IIMOL+lnISd+UZWktDfVkBM8o5LGFZWks1ukCFNKc5tUj8ezKAE+jcAgz1cR09xKTaDLjRoXMbygg0ltZy/HVkMyi0Te7DrQwZWkuHvUKFvkWWeNFZWgvQDNrUIKrlPuHTIO4f0YvuX1YtnykDRWsBPlfAlOotAGU3ltZybJxhztflagUVtxtC2YD00W7dOg3TT5bWMruppRTNb5mg7KZgQrcZJnpBa+P1GR7MlA8IRntiVmQa9Cobz2tBW6UAVwdtweBsYuQzoDVlHhM5onY0mtei2WpXI2/WsjnsWMjJyjtPoaAS6CA2jtcCY5Hjlq9nYudf77QPCMCkBT4G4A4E3z0HOYFuXUnfvBYnIOUDIqazVdOHD0h+PuvINgPqbMuYQ4Ru42gtaK6cNWwPCxnaBwRZ4okKUg0w1I3zARGTf8yXUFBweFa2FWR0f0EzHTXs9O93ktYCF6km8uEi5fykFOAEINViCkTxB8/KZ0zclLNgwBfhYhpHa4F+6qkUNOLUppFtbz3tlJGJ1Hanh0Vxd1K3BVK3H+xiJ2GiaC02hE1y15N0Lk2a1jIxKIdLy6Uy59weTJtBKtoMmL9u0s/O5t6wU66wbtXLnbw+f0useoauFKSjJu4jPkQYwEky6+vW74uu24C8bp2mM2Lxo25bqhN+OlDaz/Gi07wWI03AvUFh5umn3rTZKLx1xyUerH7qTbUZirnplDOrq26dzfJaeoaEbEPNPkt8azLiGUC3V2DmP5ZIn9+bSb0VOfxxfhqT7wSpiv+glLtbg7tbOalC1X15itfyUcJ2De831gdktgYRGpTxqYRDLpLXkkleS6N5LWouzUfFLVcryM/qWB+QAoGTbl6JYcuf8gEpybQF6124bh8wnkys/XNOJsYMrDAa5wOiBWajK7HJEiY2LK3FyP46zoO5f4EZvLC7AhaDCSiTjh4WckqBGZpRj5YDX1wcKd1lAPNgwmhVNDzqlOsyKLoM6T6EdRad7DI0TDW1JZNam3a562OvkqW14NaoGES3Gg43KRuQAuws/AwvZq1uA27sdCrsdPLHEgVRtycdxB3gRh9q0DSe1mIO9zNbOj9ub69B2N18T8Enz1f/058jULSWUTB6RNwaljGsDUjvmB+0WS8GX40fc6tbV6Fbl/WOfhQ/IJPUdSx2xcwYzVrxZ2ckrWU0FEeC/meKryNKOwOZVwZt86TWluc1YmktDb26BE59aCHfOB+Qtt61QJw21/jWZLUzBPtoNNhxGXfA/0TJJgM0uBuId63Hz0qBGYxHPeeZMgTpEgtmENzs03xA8v4xt4rRKImBEPnop/5WHMo2GZDVvazD9O3V4jcZSFbL8dbYQO0igPtNBobV0mDSIoAC/qyRuAHjZl3F8AgpQxrhrIdhtVTcl2UA/BfRLBvPapnYOaNibFhiTBBJahmQumg4RJqGxTtFakkQeIX4Uosw2Y0mtfRZDVoHGHGLl4ghtXyoEecSLxHZY7Ch4ZEyVvj61RAFR3JaJnLFhiu5b+pXpseQreVtcLCwl6ysQCd8Vs2pBQBVjR9z2wZau9wc5D9UvX87iiynpZo6kEmGI2No/hc/2cERnCDmZarc3V+UorSUbGB8+eYqxwHjpG5iF6X+4QYbPObuMmr4eiozgWUpLcM0x3tGe9bUD9x8iXUBSRP0vZl3SIbOESZg9iMYm/QSSNB0njDRYDtnZLsU6R92zgWkQDClwlq2BzCwTruADACXtEMfKKcUTck7z5hAX7bD0G9EGjSd8wGBxumR1V2KaB71u9OMiWmsVQHXbM74N2XEMwAJKrBBudCP+flbYsUzMMx/TcnXJbfycK9X11nCxKggH6TPC955VMprtJvXqJzqxsX/MVkgA9w2zyF5ieqDzvmAqBmH1Y9enfrvzWQMzSiWAAoAu/XFHHiOuxNRHTcR1Rn06jpHmEBmI3Ultr0FiXdnCRPH4YZyU+ysk6BX1ynCRKsQjDbLyRRUxJ0mTEyIURypAvjE6W78nZ7fnjKQ15uBfAR+7Bxf4jNl+C4M/YDxcK/YcE+3tVGn+BK5rwl1qSYasw/I1K9ooOtoQBmhPHSw+J3lS4yGxBsiz03jI4TCMaB+KXCAkaD313m+BHB1dhkZ4sTJ6jrFlzhOuNVGFkk737D+R2xAxt0GpM8IstVZvsREOteAjugSKDl1ji7RACbLq+q4BrDlea+zdIkyzX5vxW49yLw7RZcYqUKK+HdGrs8BmYQBthU5ZWvSXjjv4v+eVM8bvuTa+l3dRJ4flmkyQDNBIPTRIwZG5wkTcBsoAvH+vPnuiSZDhRFXgZ1QbvF1xNqATDVVE6TekJH1MwZSOANskQZJiksRzUm85x8dHbV8K4lzGJCnWMqUeIkoIMOaNp9OLVEF22kXkFoh7FEzWvMwFvLatJ3mS4hgrid6t51Mj9uI4kugJS8gRbYR4Lw7zZf4VK17O7U8b07KBmSCBpvfFhMlfkwmqyvWABJrp8q3m05y4m44lutkahAICwVoOmcDAhNPqW8abHIvTZovMSDvatZcqYefPceXUIBN0L4o4QXH8iVqMy1is2wpZ2OtbsLu3HTGzU2nBmjnTtElGnQOpKjeR1G6DRhuo4aifaAk7PHJxNAlMpropaV+P+qCx6RMqaqZUgEXlM8pedmE3dSvMJjAt99H/DUx+pxwlhDMiUPP2s6SJaRnI8ECWZha0JnvFFmidnAEJqYSekuUnMdkTjqgu49jFAL5H16jUdhdO1XfWLiRAixU57gSHYm32Ya1W+tPw4BhcYRRZoG5CgZHfouB4UpUwEHKaPXuL+FcRixXIiX4HCWQyaEq2PzLnewxmDxnArj929Lw61kZq9GU5k3mtsRnEm01alLE9a0WneKouzUqICoPpF89zBJZDxCZyLgmUP45XYreuom7a3mvg75n86YKiwSKLQHyiaD72yUwauk0W2J2SPoI8N0y46VngAwDTs111LuvchCQ8oNFHp+gqQijlvlhCPEcdpMxrKTTaChdwg4LQ5boKLAF1sJtBvPCzpIlZCiaXx3LH2K2OkeWmADiw/klRBB32gNEIbqTE045UCdEHVGGTpuAgCDVUHr1yLu2cyYgAs0ZA/7JjVUbB4zxQOjXTLj1aguHHZQJCCQ4KvrIutmXLFkChEA1M5Cc2qY4IpEMsEFuHfpqKVBQ7RxbAtmngN/wAQKLA8aygigxBTOe3AKV206xJQraf+aloz3eR6w6p3lmNcNu1R54C3eWLCEJaoodDOCf1tpnzkCxJVATCKzyLknv584S6wLyesxVwGJwojWssxm2RIGdYWlvdU7/OlJWlAEzzRfpKF+ko+62PlkTkFFAaFnbbjM6otgSIP4eqXe5p3V5GzBM66bZWIKNkHuYenNsCciRwgEmawi4YNkSNoDTOhF13aEX6SgHcXcTWKBN4H2j4RlCsSUyaDHoA7UR9tBptgT0kY4S8W2/59+aDFuiw93seMq60zbpvAuIdWcT8DAwtZT50Qp7jrvrMqw+d+4XhFjcdJ5zAUFfuqzluTQenktY3gXEiCcKYfwRoNE7RZdocD+pMKr58GmW54Cc4ZHZ7uW3ELH4MwSaL4FBTAdABqJO/ndPaT+m/J4djfHVYxE34GZOnt9zcnTrgm+J4kusM7kUKFykMK8j+RIlAaukAyZ0aAVJctNa1gakGRZILotd8Tcn1WfA8Kj0cSfJOIvO8iUwIy6i6Roe+bk3ZQMCuEHpv6IMTkBmjWBboWOahNcdtZWef04qZ4AYAwAynxbAP4/KdBlwyN3loqv/wbNWowPeNxAngPxMsESMJsNYfZrSe3qSi9bfgAz6sRr6sWJzlrNR255TBrLLAEJcw47vMyzfKbaEnUO6Ctl27qC6DRhn3ujWZYCSN1Nyii2BD73YbLfGeSKr/Cgm8JBNxj9/S22JE3cLUBVcR5duhvjHJwNlqHCPgWZKzx/OblHAGMoAAoqgOEg5BCtSfIkBHAgGFKGMU2f5EkVAL9QJiq21GYLce7AbSd8baaSwXUcRJqDrIUboqPGvyWs/AkQM/cuiYeOXIUx0uL1U/U0Z9Dkg5cAHuXW7lt4d1eQ/J5N6KwZ864Pv8fSII0zMeoOb9MADuNOEiWGapLhDwAb1jyaGMNExNqowycszHBXnRDe9szW9+6W0FYCIMw1lgCgDBn0tzG4yBWUw1fXc9wwM1gRkGPdkACogcVeAMQF53R1wJ7+GsDkOSB11psLR9Qata0TcnQEfzHoheTkCuZjBkVowkjDr6x6h+wdLajmOOhiQYUCB//bSusGRWhRqKaXn78nEd4o8aFJLx+GhzbAM0m9YBuftqY4qUAygNY1IJX1wnBaYK9hZ16Ou9+BdQDI+d/PETZF/6yBdQCZYsEjme3AND5rTcsS0KWwFT+rsqI6HYnPQnJaGo04gx9KDq3hwnBY1cU7ErUG5NWgPkJGMv4eyfdb9Y+6ViMtbiVij1tKgOS3NDK4a+nR21OX49ZnrCJ5U+Jx6BLwYFKfFXl7ACO0tSGkHbwJi1xF4xdLr1+Z8eMzt8AgyDw2Lr/HxwZqANBA6jj9wHaW7hXwUdycSVEFtWGt1wW3yc1CG1QL3Til53Nlmsg0YCznBNj4BmDtzkDMMitXS4YxZgQrJ0Uhm0KwWaWD8z26Ikxk5tQzaBgTWNA2u50NvsjYPz0opZ0CBBlrJvQccy/EHbEBM3QSw5N31wbSCwNwq7Z0zZP9TYltBYk4t6KUagS/5KVP7Ry6kEe8jyg8WYlvQ7fuYdUgYcKMrqDddwRbZng+K1tIh31UNGxJZOQ6W1pJ7MrGtAgPoUYLqcPwBVkuD/t9anhmV24OzAQHD1NoMrcVfPIs4GWYxAQ/PHIHhBsVqGQBT1jzTtyuV85iU2pbxAeHcCjBcc4Zng2a1mBJa0fQNhcu/JxMFOLGjrl2T8uyfxyyrpcCCrWm70PjBycRIZwzzsewfgt7ZD0i5FyBXsDE8ACftI795DrshHoHAZ0ocJbzgGVJLB1lAav0hm8UBw6634O7IpofWwpOOMgGByHyFRWQuX90V+Q24fst/+fvf/vyvf/p/L1AcpPXR8LPpIyiBuvkV/7hyl6nG+NcGS5GBUoyZYfQcr7hQ+Ud/5x91hhmysH0lVAfHBY8VT+GNyVBkKrrcxbSM7j15/V1xiVZcJ3zhElC5J0E9/hU5jPM0jHNHpXlvyEsQd7PH0ZCH8GPPYZnJMW5gPFfWO48Srw0LhlFUawO/pnwv0EPUXcZZYaYK+PCHN6DzmO6KT1xhL6lx3Lr5vHuDX5HJX42i2BFfxwca9/dUJwk8E6JNpuS9UmS/wKLcThRO9gYDuWOpNAwY9yXVRjD5sgAo/snBKJHCS7eid5hnwLEaN6bN04ofZQq0+ExxWS4VrF20nfQssMcN6hu6Cvbp7x6yO9MhxzjXO0OG1v8lOcWRelMcGYGt+aDpQAPCPS+JZMyyg2nr4OhA0LkrY84dRH7caDuPhzp6CDn9f5VdS7LcOA480USQ4A/Y9mJuMfe/xshKlB5fWQCzFw5vbIZUFEEwmR9YpAKWqskSJ0k/Falt1wKCNXKbuxr5mwWhdBILnOonRDbTEhc55ZJYsI1dS7ztgUbtOGDeW8Mnc0Lfu/bGTd5HPV09NCdmga6w31a39wHDGe8FDt21Q0x2P6NIvBZZCpF67CX4kiAfT2LYQ1yfI68/8bHJLk4JlRwkB+FF05MpLVTq4HEX0I5lnkc9HqYa7FDm0Q5FN0XRy4Rf5zHUHxfWwGNEYoSjsiiUwv13LV/iJQnAU1b2pAuuhjBGnZoeSynZkyDHBwFWv/IZazpgbt8KO3EPj6iHoxlDSFqo6R4QNPLucmUr/Pp04C86UNOxLnv+K1KeVMDvtYJXL7K76bwcIGk32HvGy/15plEZyomohqem3rQhAM7UgP8GdpT0qpITUXW46dRH1JvMkWZLvJgbOALU6WX+fbP2PtoxB6p7DtS93WAlRdwzpSVZ7p+NhLoHwX1HihhJ1uowRUSqw+OKKccB874N9yroLn+K+vutGiPJanBavJpM+S7q9f0xk0b9PkVcjTrsPrzEh7wBVuA1cHMqw/05zBI7AGUFXlbQDYAvhSyPgKutnL4LnF0/i8+RuFIrnYazOr7yvW0r4Ypk9F3T7j7VtaxNU+RWUrxNzY1pER3X0aOPcMLZbJ1qOOOZeQ7j+oxbD095cmG/+6uCIJiSvzmDt01widvdAet3+a3hgLmN3d0AdpRzkd0cr74/5mmJO/oCuln77R39+pjhjF8dwV3UBYTVBvBOwuJLi8+K62wX/tZPPn07PORBCm2IMYVvYc0nnMsDdk/3X/zX9zrEas8MOowG+0K4f5awN2C0ZwOXMx3mMa0kxge6acReJ9yKL0EArR7KFqKBbO7PQr8mE42W3GSRMAFaaSXbRIuOHJyUp6qcks2jVKDVV00xelrJJujbFF48Jomju3LBP1DCDmhMm6aooKRwmyHovLnkHf1QtfylKV2cuS7OCWslJRWSsjjrHnsi9WRNqlyK0ACK3vAFjQ1ua+mA6RL3XDO4EaONiekrjCpuASMZuHxsK/+CUritD7g3/fHNuGs6rPryX5HZxcUpVfBdxwEwuUNhNXbwPJywT10jERQrp7FDKapwSpkrRS5pjZ0gEKCAWmc1r0SMxs5NMubQz/wcBoyXeJ24x/Sdpz3BAu8kA1Kx1xTF8s/HCSn52KJFs4c8pShPpCjrnjIZvPiff/rff/7zz5/X/hmjhH/++s/HDQHWtdAErJ6kjCkt96vlXnQdt1lSR4ohM3K/Ue5FfZ0e5n7HWuP3jrt8cOpbVz/I178jGt9HO7nyu42lAPRdmqINrHiwenS99B1aC7qKRR3r0PPJ2hU67yAYHbU04AmB8FDQBpN9iyGM4e5uIOahzfQcLytFbqBovXZobAx3zytJ58zSz6YbtahHp85fdPV42AOLE0onJwrmTCRKiFixwnGvoSMFbmghIi6Au2wszsNjHk1AEGFSILjPKYei6X6AqWjDkx2wbyc7NemepB+LcxgJifORfhlIvY97OMdDeoro8rmDLC8tmlEzDk4o7H9nvhhpqA7KM0B19aBOYWSNfUE9tNyc/OtOvf49YHysmxWpeTCdQxxj1RiuIqG61T3GA02as8Dj0yIJ1SmSpHCVtfImnxFJLjeWBP398bF7v2ElRZJS4IJ67Wsg02uKzTIiyT4NWuNue8uXvHc44ddneJeJ+iFRtI+jfY1fmlnint+7PpTissGe2bCHCzf4aMAwfEnKHmEUl7OCbIWY9mnpWmQVl2tBt+ri7ZKDA42KqHIwvvZvxWUwYLyJN6AfwwAgQ0Exw4uxxgZeoVb84UkBjJfM/VNp/SaIQnPeZ4Y0Q8wo/ebycAnEYmilB8zbNvBTBdqOkSnqjdJvfrZcZBfj7imYcduElu/sVxi4uw1z+1EbnkY7OVvD6tR5Lm6/1YKm2lg5qLpiF2ETM1O+G6UGXd29RPvDhZQgacB4NainXM2lDzg74hlnwFlozLrO9lnjEbvHNtnm68kMl6qtD5QNmNFGldJYbelVK6BP9l900/KUw1MeeDPIAoACQ/fj3stXxHAhFc6kngs6tl6jpQPm4lJQShfqx8qAFqPEpQtS3U9sgyRXeLaJQF95M3K/anPSfPcY2CAJwFip6nUsQRtduktVyzeNIhr3xH6FAYk+N25RFJdxUlU1V0HOk0e00VJVxcHE+c55woBRUtWG9IeO7Vxm4gNmm6T0dcane+urOWLw7ZxagtEOxJmBmVZx9+Gyo7MlGTev6g22h4a/Vv6tU7pXeDehv9RDY8CSIf02a6HOVUtogcalucHHpc/ycONaXC9TdHZ9NH+g2yGtUmr+KzL7uPra9oPpqF8U0BoMe8Db1O9YH+/IZMKpbDiXNHQ76aDsX2TDgYdSYWxRZnJ2NkpEuyDwHvCUapLcsdomdn09m0FQ1Ip9YPlD8WWT5iYkufNjdtgSdxCjg+ZwMzanPaYbJS6WDMAKlmaFi++j9mzvD8kCrPXGCjqO4aD/jrjZYMiQQC/7h/OSmPbYJp19pzs7va7jAAknj8OvSOnkfYUvB3Crsyjq4SEPjokgQYJpt8YXfeRrTIYLqRUlHXnRNaGVGh9ahwDmDvEKUPAR/6KU01vpP46Jss4Dxsw43Na2BvUkjlASwW1Gi4XL8gg8d7CtWeiQ0WJhXIFP+L5PzSecEgv7DSP2iO8VHg+YlvQJV8zi3PHvzqD+PerRDngCUdcnNLfFRTjFV0UWuirUH4BudRGjnRT8kNfPDtqzo1r57DBdG9zYbI19E3//1CntcROIlmR+VGpxsWQD9UwBsFanpIxEeGGU9nigyej6Ex7a8gHjs/iE936HWq27djIsvmw838C1t1xfZX8kLLWEy4fVHisobPDH1MOMMwgrAOYKsofu0KV8KauMj+crsEgDlgd1s8TfEYO3VbgTuzn34RNK8bYGxdtV08d4dtsQCTVae3wVdT+Dg6E7LLkXNzrsr97t3xyINJV8wikuJMzXYE2tIyG/Gi09Xs4vhU76Jwm9xo95pDuDGYds9V/5wPV9wETRgHU3sX/DsjMkNBktPR5u0TuKe1GNfMKFnXDw0O+5npbu4pTyGOrt2iF7kxT7ZqMDTRUHMzCGvi6dX0c91nTwFoEUiSVaczsoj68i4fgqQPr63HW0+PEYtK3C56QUryCyWclmD3mCV9FP41JT8xVOgW3g3G99erIWWSqkGn7LDuilJm5BRimPr+m5AXUwsmSmgMFBeaww+CiztsdcoK7w3Egrj80/RsBiOEHX+LqDVR4rHJxw8bNaPuMM2PbLUHNqXizZWEPDDoYMU6kzhUoY5fFV0ytq+q84tmTA+Cj+SRitAMXgEJ5s4iTYJsOXeMM1z09zUOMfkyG/DlTzH5P0GKmmpMfIQr3atrnb3J4HTAH1jmWkvsZXXjkYyzoEM/U1Hvg7ojtbLj3u4hz5ItCcw8xnxdWXlR67ae5ynvtaW1yFJMMezuIgixcwYEYKQlQObVtfKWQtfkgebRs72ja3HMfgMY/strtjGQVihJWYnNpJeozPsHkKKjSzNdluSTrjgIDwWukobOMz4SN+638bVTtLIrI3Snns2Rx13OX8CXvpD2MuGvBgkgxZIuwznsTnGo96zjRDFlMfe3xjMOGayxJxnO+2idRqy39FZheHE5a4H7wrg3adTQ/GPeziKOYFYXbf981fJ2dKeQy5zrh/Sq0ps4JWHhf0wuvLMSao6UxKA+7dBq605XBASeE2RXZE6108K36P6SzJaCf/ENB1zQUcY2wesZIMezCMEUTXrSc6JW5YOeWxn8xu7seqiYGz0cmSxc9RMJj/4Tolo54mfACVlx+0rYSAba48FjcoKCK4I+2fmt7ix6MC9vABlQq16JA9QUKScQ8qNdcWrcdhO/kpGbTN4xndImik1810UCVsoDugEvmiA7+Oepjxq1R20FT6txA1GDAp6iCudnf8MznMOJ1H0bHEF3gWd58Zt22s8hhZr3OusgcgBi9ORR3ARx0C3Ed29F7T6dTLjs5IAb4USaTmRimPp8ARFJfjbaXHiVx53A0U8murGQ+dMWnb6AzN4uqT4q42MzMtMFZ5bAuG0mYPoJ4scUZ5DBKw52Glhu9GK489b937NpjTx4A6pTzuFbqj9TTqNX/vWJQAFdw14+uHoy5CjHaC23yzABsNhBojhj20bQLw5X4HbSkxicrjbLguGvJsEvGpVGhu23CpOUJTLVEzGaU8dg/p4ctopoTYXHmsFeSZ7ncc7dEHvd8ikMrj66Tn90XmPNaW5UAZqzxWuMnNdiuuZs2LG8Vtg0ik4+hY03txWnmsCJSq0HGXlSgBjVIeN3To3WWBmW+KHZTHbjh5LW2bz1JMqE58Vigkrmr43EvftrJs2MOE34yJCf+h9SLS/N//AQ==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [day = nullable text, campaign_id = nullable text, platform = nullable text, spend_cents = nullable text, impressions = nullable text, clicks = nullable text, leads = nullable text, mqls = nullable text, calls_booked = nullable text, closed_won_deals = nullable text]),
				  #"Changed column type" = Table.TransformColumnTypes(Source, {{"day", type date}, {"campaign_id", type text}, {"platform", type text}, {"spend_cents", Int64.Type}, {"impressions", Int64.Type}, {"clicks", Int64.Type}, {"leads", Int64.Type}, {"mqls", Int64.Type}, {"calls_booked", Int64.Type}, {"closed_won_deals", Int64.Type}})
				in
				  #"Changed column type"
