table mart_link_hygiene
	lineageTag: e5cfa325-3f3f-599f-85cd-a282dfe4ef82

	column link_id
		dataType: string
		lineageTag: 83f73821-e7b2-56bf-a7f2-9459e8a6ed67
		summarizeBy: none
		sourceColumn: link_id

	column channel
		dataType: string
		lineageTag: 075a90ca-cb8e-5304-8b5c-69cf02ab2524
		summarizeBy: none
		sourceColumn: channel

	column utm_source
		dataType: string
		lineageTag: c9f03021-a5fc-520f-9ba0-f41ec2e81393
		summarizeBy: none
		sourceColumn: utm_source

	column utm_medium
		dataType: string
		lineageTag: 95e696d5-28ec-5e3e-a9b6-d60cb26bbb17
		summarizeBy: none
		sourceColumn: utm_medium

	column utm_campaign
		dataType: string
		lineageTag: d7b5d9e9-ebe6-5006-8a65-b3ce35cc5b71
		summarizeBy: none
		sourceColumn: utm_campaign

	column missing_utm
		dataType: boolean
		lineageTag: 746d14c8-6a2b-5a4c-a134-4d4d3d34b2f1
		summarizeBy: none
		sourceColumn: missing_utm

	column unregistered_campaign
		dataType: boolean
		lineageTag: 992d2601-8621-5985-a771-221f38a346d1
		summarizeBy: none
		sourceColumn: unregistered_campaign

	column off_taxonomy
		dataType: boolean
		lineageTag: 1bb626a6-8414-5bf6-9890-ab608421acc4
		summarizeBy: none
		sourceColumn: off_taxonomy

	column clicks
		dataType: int64
		formatString: #,0
		lineageTag: 1d896644-4502-53ff-829e-c181bc2bb1b8
		summarizeBy: sum
		sourceColumn: clicks

	column recent_clicks
		dataType: int64
		formatString: #,0
		lineageTag: 7fba0ae5-4039-51fd-96de-6ec7a531ad21
		summarizeBy: sum
		sourceColumn: recent_clicks

	partition mart_link_hygiene = m
		mode: import
		source =
				let
				    Source = #table(type table [#"link_id" = nullable text, #"channel" = nullable text, #"utm_source" = nullable text, #"utm_medium" = nullable text, #"utm_campaign" = nullable text, #"missing_utm" = nullable text, #"unregistered_campaign" = nullable text, #"off_taxonomy" = nullable text, #"clicks" = nullable text, #"recent_clicks" = nullable text], {
				        {"ig-bio", "instagram", null, null, null, "True", "False", "False", "3568", "910"},
				        {"li-launch", "linkedin", "linkedin", "social", "linkedin_ceo_abm", "False", "False", "True", "139", "139"},
				        {"nl-deadline", "newsletter", "newsletter", "owned_email", "newsletter_weekly", "False", "False", "False", "271", "271"},
				        {"nl-guide", "newsletter", "newsletter", "owned_email", "newsletter_weekly", "False", "False", "False", "6362", "438"},
				        {"pod-apply", "podcast", "partner", "referral", "partner_podcast", "False", "False", "False", "1207", "100"},
				        {"pod-ep41", "podcast", "Podcast", "referral", "partner_podcast", "False", "False", "True", "245", "202"},
				        {"web-invite", "email", "webinar", "event", "webinar_growth_os", "False", "False", "False", "4001", "290"},
				        {"yt-guide", "youtube", "youtube", "organic_video", "youtube_founder_guide", "False", "False", "False", "9977", "694"},
				        {"yt-q3-guide", "youtube", "youtube", "organic_video", "youtube_q3_guide", "False", "True", "False", "892", "374"}
				    }),
				    Typed = Table.TransformColumnTypes(Source, {{"link_id", type text}, {"channel", type text}, {"utm_source", type text}, {"utm_medium", type text}, {"utm_campaign", type text}, {"missing_utm", type logical}, {"unregistered_campaign", type logical}, {"off_taxonomy", type logical}, {"clicks", Int64.Type}, {"recent_clicks", Int64.Type}})
				in
				    Typed
