table mart_measurement_health
	lineageTag: 6c18905f-32b8-5526-816a-437e2fa32b4f

	column eligible_touches
		dataType: int64
		formatString: #,0
		lineageTag: 7715f9e8-14c9-586d-947d-005be2a5419d
		summarizeBy: sum
		sourceColumn: eligible_touches

	column touches_with_utm
		dataType: int64
		formatString: #,0
		lineageTag: 77dd0787-f901-5b12-899d-56f4da35fa07
		summarizeBy: sum
		sourceColumn: touches_with_utm

	column registered_touches
		dataType: int64
		formatString: #,0
		lineageTag: c461e749-d6fe-5710-8ad1-0257092bd7f7
		summarizeBy: sum
		sourceColumn: registered_touches

	column owned_contacts
		dataType: int64
		formatString: #,0
		lineageTag: b3d3ba6b-6a70-5e3c-8b89-c3d5be30abc5
		summarizeBy: sum
		sourceColumn: owned_contacts

	column contacts
		dataType: int64
		formatString: #,0
		lineageTag: da3e8467-389e-5166-859b-b16fec74bb56
		summarizeBy: sum
		sourceColumn: contacts

	column duplicate_contact_rows
		dataType: int64
		formatString: #,0
		lineageTag: 20852050-38ec-536f-ae28-af7e66a58c40
		summarizeBy: sum
		sourceColumn: duplicate_contact_rows

	column unmatched_payments
		dataType: int64
		formatString: #,0
		lineageTag: 72981779-53a2-5e0c-b933-d85d13c880ee
		summarizeBy: sum
		sourceColumn: unmatched_payments

	column payments
		dataType: int64
		formatString: #,0
		lineageTag: 68a62949-847c-58fd-a2f2-0ff9ffe5ea7a
		summarizeBy: sum
		sourceColumn: payments

	column paid_contact_count
		dataType: int64
		formatString: #,0
		lineageTag: 0b50c993-5d97-58cf-b56f-cb3b33320e0a
		summarizeBy: sum
		sourceColumn: paid_contact_count

	column valid_paid_journeys
		dataType: int64
		formatString: #,0
		lineageTag: 7862b8db-ad32-5d36-961e-ebfde9cc684e
		summarizeBy: sum
		sourceColumn: valid_paid_journeys

	partition mart_measurement_health = m
		mode: import
		source =
				let
				    Source = #table(type table [#"eligible_touches" = nullable text, #"touches_with_utm" = nullable text, #"registered_touches" = nullable text, #"owned_contacts" = nullable text, #"contacts" = nullable text, #"duplicate_contact_rows" = nullable text, #"unmatched_payments" = nullable text, #"payments" = nullable text, #"paid_contact_count" = nullable text, #"valid_paid_journeys" = nullable text], {
				        {"19855", "19360", "18343", "14103", "14693", "138", "9", "809", "427", "417"}
				    }),
				    Typed = Table.TransformColumnTypes(Source, {{"eligible_touches", Int64.Type}, {"touches_with_utm", Int64.Type}, {"registered_touches", Int64.Type}, {"owned_contacts", Int64.Type}, {"contacts", Int64.Type}, {"duplicate_contact_rows", Int64.Type}, {"unmatched_payments", Int64.Type}, {"payments", Int64.Type}, {"paid_contact_count", Int64.Type}, {"valid_paid_journeys", Int64.Type}})
				in
				    Typed
