table mart_experiment_variants
	lineageTag: 7eb4dfb9-7dd4-574a-9bb6-d527472c7261

	column experiment_id
		dataType: string
		lineageTag: ebc5e558-074e-5d2d-bb07-8c21597fb03e
		summarizeBy: none
		sourceColumn: experiment_id

	column variant_id
		dataType: string
		lineageTag: 91e5579f-16d7-5d34-bd69-ea4b86d7ab2b
		summarizeBy: none
		sourceColumn: variant_id

	column label
		dataType: string
		lineageTag: 06479227-62cb-527b-9062-e40a59bf1823
		summarizeBy: none
		sourceColumn: label

	column cta_text
		dataType: string
		lineageTag: b5f8fb34-9147-5e09-bbb2-00eebe8900fe
		summarizeBy: none
		sourceColumn: cta_text

	column visitors
		dataType: int64
		formatString: #,0
		lineageTag: 249c45c8-f834-558f-b646-c353608d8628
		summarizeBy: sum
		sourceColumn: visitors

	column leads
		dataType: int64
		formatString: #,0
		lineageTag: 4debae55-e457-506b-a97e-74593eef68ce
		summarizeBy: sum
		sourceColumn: leads

	column mqls
		dataType: int64
		formatString: #,0
		lineageTag: bcaff9ee-7077-5dd3-b18b-c80e783ac8f9
		summarizeBy: sum
		sourceColumn: mqls

	column customers
		dataType: int64
		formatString: #,0
		lineageTag: 79ef3874-4a61-5e22-8580-9219898dd212
		summarizeBy: sum
		sourceColumn: customers

	column net_cash_cents
		dataType: int64
		formatString: #,0
		lineageTag: 59075a7e-f59f-5bd2-aeef-c09faa0e79a8
		summarizeBy: sum
		sourceColumn: net_cash_cents

	column lead_rate
		dataType: double
		formatString: 0.0%
		lineageTag: 9374997c-7e65-5129-a6fe-b5a37c3f70ed
		summarizeBy: none
		sourceColumn: lead_rate

	column mql_per_lead
		dataType: double
		formatString: 0.0%
		lineageTag: de1fe533-3860-55e4-a8bd-6383b743acfb
		summarizeBy: none
		sourceColumn: mql_per_lead

	column net_cash_per_visitor_cents
		dataType: double
		formatString: 0.0%
		lineageTag: 44207507-b41b-55e9-a5de-34cbe42e20cd
		summarizeBy: none
		sourceColumn: net_cash_per_visitor_cents

	partition mart_experiment_variants = m
		mode: import
		source =
				let
				    Source = #table(type table [#"experiment_id" = nullable text, #"variant_id" = nullable text, #"label" = nullable text, #"cta_text" = nullable text, #"visitors" = nullable text, #"leads" = nullable text, #"mqls" = nullable text, #"customers" = nullable text, #"net_cash_cents" = nullable text, #"lead_rate" = nullable text, #"mql_per_lead" = nullable text, #"net_cash_per_visitor_cents" = nullable text], {
				        {"cta_growth_plan", "cta_a", "Control: Book a strategy call", "Book a strategy call", "7951", "524", "120", "6", "5130000", "0.0659", "0.229", "645.2"},
				        {"cta_growth_plan", "cta_b", "Variant: Get my growth plan", "Get my growth plan", "7940", "787", "155", "9", "4440000", "0.0991", "0.197", "559.19"}
				    }),
				    Typed = Table.TransformColumnTypes(Source, {{"experiment_id", type text}, {"variant_id", type text}, {"label", type text}, {"cta_text", type text}, {"visitors", Int64.Type}, {"leads", Int64.Type}, {"mqls", Int64.Type}, {"customers", Int64.Type}, {"net_cash_cents", Int64.Type}, {"lead_rate", type number}, {"mql_per_lead", type number}, {"net_cash_per_visitor_cents", type number}})
				in
				    Typed
