table mart_growth_daily
	lineageTag: 00fdbcaa-5527-4ad0-b974-2884a3da3fc2

	column day
		dataType: dateTime
		lineageTag: 5c0d3eb6-2914-4bcf-8109-eb6411e8f400
		summarizeBy: none
		sourceColumn: day

	column spend_cents
		dataType: int64
		lineageTag: 8eadc0a6-24d6-4e55-9e8d-1da9e0d746f0
		summarizeBy: none
		sourceColumn: spend_cents

	column leads
		dataType: int64
		lineageTag: fe14f4ec-b106-4984-a8da-2c8bc4b807a6
		summarizeBy: none
		sourceColumn: leads

	column mqls
		dataType: int64
		lineageTag: bb299807-3316-4af2-a72f-ff4ec86560f6
		summarizeBy: none
		sourceColumn: mqls

	column calls_booked
		dataType: int64
		lineageTag: 784b65cd-41c7-417f-97e5-3aa5940c254b
		summarizeBy: none
		sourceColumn: calls_booked

	column booked_cents
		dataType: int64
		lineageTag: f128ba25-15f7-4700-8d9f-4ae185b25f09
		summarizeBy: none
		sourceColumn: booked_cents

	column gross_collected_cents
		dataType: int64
		lineageTag: 311b61ce-2e4a-48f5-bd57-3b7c8c583c2e
		summarizeBy: none
		sourceColumn: gross_collected_cents

	column refunds_cents
		dataType: int64
		lineageTag: f78e9503-b825-4e37-afa0-ad639353fa13
		summarizeBy: none
		sourceColumn: refunds_cents

	column net_cash_cents
		dataType: int64
		lineageTag: 096b67b9-ea74-45d0-bbe6-53ddb9d46679
		summarizeBy: none
		sourceColumn: net_cash_cents

	column closed_won_deals
		dataType: int64
		lineageTag: a7655984-333c-5a4f-b91e-9a8824168d91
		summarizeBy: none
		sourceColumn: closed_won_deals

	measure 'Daily Cash USD' = DIVIDE(SUM('mart_growth_daily'[net_cash_cents]), 100)
		formatString: "$"#,0

	measure 'Daily Spend USD' = DIVIDE(SUM('mart_growth_daily'[spend_cents]), 100)
		formatString: "$"#,0

	partition mart_growth_daily = m
		mode: import
		source =
				let
				  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("nV1r0t0mDN1LfzczSAgBa+l0/9uojQQWhgu4nUm/3CTWxaDH0ZGAf/75Cx2GPy7+cfDX33+lnAmvnz5e/3M/f/37t3nu/veJAqb7ufsDnz3n7+eiS6l+Xz57ju5/ihju8Xo4/75Qvo/p/onlZa9fsH/uFp8Sxvsn3mO8BdD+uVjmBeQ50Pc7+L5Uvo/z/Vfk9Pv8/rlbfPY53//Us37ffpzgyjjlOb4/lD/B/YNlDkMO7Qvh/ra4f7BoTCa4Xwzufw/+bKhFZdiX2YSyfHD2jVQeDEVXy1BZ53Xz3P1PsvPh/hlInzsYaNGZfGn3/X1UB0qqABDc/V/3O/upExVlllOZIqzLQ7pEOZvnJwNRZSrKX5S3PG1njJKRoB86EVn0g8pCYfufEQHRvkQcRGBRscsWimLFYxMSK6VcTKIsW332mUX7G/OhE4Py9VymMNrV2Hy/F0UtptjU5nDqsehcykWHCKqWW6VjO3CeDDyICykvUJYyHrk6LOoXffHGRUhZMn848OKLwRfHXLx6GHT3lm81N42KW55MOZS59k797WgCPwZRtC64dA+YvPFm/dJ3UwiTOZRvvty+r+GpumF4K/84ihJeUgxFAWUi4eUb1+aTNKyGSxHuBzvzuX8FWAwgaXCNkag+nfT7fRkM6dPZWmCO4yiKJidXvEmRcxJUUg22XoJtGz1XTeL16Iv+MpTRP74rvJ/ezmHRZx+LJyWx8sERlD8msuqgnzpRRbldFJeSq1XamYhWpWIYRYhPzYk7pQj7yRRPylRUgXQx85kmSJj2LoO1Sn/shZPGa05PvI4HXjBJuM6Yy6s+q4j7B0XpJAqWIUMNoZ3t7ZZfo7fLWD0JsHEGSxtOGsMvb1YmztUV5w82XL4uO/ChfnedvZOFKwE8ZnHG1YS5mnDTWABv108/dZKK4gWKt8r4uvzVFpmPHHPSgB5IPFIyrrWIqaPwaMToByumTGV2uUB3gRbVsF9Gme301k+dKJAALXG2etg6ouf5HVpKGuoDUPNzWSe8n+zOcemHTk6JOI5KsgB1qocAKovUBuQnAyKBEOys2e5tR0J/9KnpvLfQ49RzChLwoTjN4u6yeReAqrpsdY9H1SuYIN1f28BMNb9O9x6J9lMnSbynCy0tgjem3jkywQbO5dwsGswEGX3ZCFJskMuYsEVVN6rwdp0FKSSQAOsm2dc6rGQFCpezLBIs2OzH4m2I8zTKEciAZST/HzllxQyeiy14Z+OcBAFc+L0s0OF6HZncbBOXs4XOih9CkIDpLfwqY6u6RlYOTeQUKwic8VPEzprDM0oE8y+P+7iB3XskQXGMNR1ssavMzWkIyAohMhTVL9MSZxEVvfVv9ZMVBOK9qYAY33JweEeBdW6VFVTEEEpmFgaIl48cblZO4PpzrNpS2aDuxXYzXSFHwatCLdSpFvWJp++ljEF5JXQ2cX7FJOpcA7lRlJAIgTsCiYeZxi5MYhoFKQwmrnmshVPtjdaBOysgSRChwtAwCy3bqU7KjeTqHt5J/Tq9zQJEronJ90M+aaB274lZx6Zc2QVZ82Kk8YWM11EyN/whZl6dd3UzsT7dgkCTd03CKAwNWkULs3tN3oSUrOxDdGWiH9qi+V8+d+WCQli5Xdy+oPnQiSn+OEcOdabz15lWZkLWCmzoLtPlYBlTBIYwCxCvhIglRVp0xOZUJ+9RWTGoS+RfjFa2NpRHGxIPhVygEHmDqcpCc52GZHU3jborCIRdaCbQSKJeW9ZeBpzAhwtvcUgtWKJ5s5alLPHDLago1+1/sKYZnwDaLUJ8bSButEEyqcEqYbufFr7UU6E8n7BP7zdZ+pdbkER6RKGKKyU+GtDSY96CWMiWSI0Smyagm/zkliRm7EPJvymYTPB4coX3hpiDzePjezDb2SmQDFgKKdQSOD41g0sGKMq/fMI9lh4925i09OG3INHea8ljhWjZVGg2GiOM2vVf8Q/iVvAL13rLED273EZunD2aWHLmJG9Bor6AwrN0kOh0jaUycgWFMhO+Mbj4RQarGfGDnvnrOERdL+Qc66Twz0Jd96AoaVC6Cgzg6UwYnOWi66dOUq6vgdX2Dmir60FNDL0vaold5WTLQN/Pi0pCKD6arC70r7CZQ/lm8FgIKF+XYHDxLT98UPxEWPWsxROJloYZn91gXAr6s8jvhVGFxA2qNIRR5oz4PbZZ7npLEn2NHFM31w/LFc8Y2luWjOMCULGqbDLI21ANnSSYSIr6F9wgKr0MYBcMhbUEBqkdkTXmnoGH0GcUk0mSHDhl30oRjYl8JSeuiyNudDKajiOWqq2MEl+BZPduhbK4xgNPcdCGx7MUEKAiD6DcylTgXmNZe19Q0HEtuVTLq7Hlgbib2SpUwMEcmr+MM8CxHUaFHgLpWjxL1mdyR3ExjFLEGq4cMVQjnZXinyziDZRvGWIFASSK0CuNeJzXOkRDRRzBSfrJs9VZuzCokONCHKllwxZbnlVib0HizF166lnRUpuOjpwqVODhffE8YujOSMNQpwVS5yYSjbJEfzEKr94Rxp3yWBDC45IpCnGumDbFF/PWAsYyR7rliDL7WFYsoMW/nQckGzspj4JIPWlRH3EZ0bAhVFcrWkFxIkjdu4PmtACnpOJm/RWTBJ+kFKDejwetXgccqMDkwtGt60hojU/U3C1IVJtAsF0wtYdT36UIRdsUkCZZ6dxrVYQSxBoqARI+MTG3HFHgK/NrJS6aKTBgRy+iHyWJssXo2TbX+CEkrGn+W5LWF4DQcuv0P8YkWhyiLLWblFB2FoU1EYxUC0zzNGVnUYpNEPuQOc2NowKvHAYp4q6SD84yVuEImELFJFc2mhuzbkmUh5vceSx9NqDEhkbxN2/TKMngrRHUT1aWIhLyYczaV2aAFT8wSlzyLxxyaMrYiItLe2ubQPoEQ7DiCNKcmGxr2q5z5n5cVNV5R5Yn+J2at1calBYVRbjMkviALUSeKT4qinDZi+LmVy/PmHtM3S1WEMFCPTc54ctQNCOMxQYbL+r36qHulYXv8IY/Py8NXHIqZADXBjA0su30Q6FCIm70DcxwZtcSEGCUg9WEscKXNFuXZdXkliP66qCQ8EA2MBczhDOsgBUrOCiYFbLxScJoYuNV7TwjTSZavW0QbMYTAnGnLIoTrnjT7PBtymvci426cKH10do2h4fLX9UObznqbYWG92C48zP4jI3C8KZjiCwn2jdINPf/Z2QQsYKGCKmSKlPNwQ6KIYy6rKgBSZQxTLLjuUFqep+FVsW6MOlTH8otR9IrNo1U0RjUWY/DLUdpDO2rQsMbCouRm+p2VVEa7UmBAoGPlv+jIUNnK4kngsTxBolFkIzDOtUaZS+Yi6/p1udR4BPnjZWLoyfKz+AhdjQ4+tGmFC9wdt42QuGQBrg4MOJ/yA/yFDM4X6gejEZe/4pzRfRa8pDVaiHFPtCL8D2Twhf0UPThEgPbfQGH9i0ilOFz3PrD4lF/mjyt3AUm6rgz/yaes13nHMZhaLoX5U3IUEt9uWNBxougyj5zqsxnHtBy0RHsnAxOxqQkdJS6t+0C/ulk5MGo5SxsJcvGKK6b7uRxZSx8UTG2uz26JVlwZCInK+DH1roB8RxUFhkKPBB8K7i36kT3KiNDMK6NIhB21IKrZUeb09wOSsGyoCq0tbHmsq07SDiKUC7a+24HD51RkCJCVZalBcBmQmv1EIzhkhNSPZgdHae9ECJH9TO7YHMP2A9ACQhBXlhp8/R5AKKoLmZ+19S7YLqVkzUol8y9MaB7Q6skhKT8AWflqh9Pas0OpDGqIVC/f1IdpsC7vrXswGNqcullH5CwtFO6d4EcRBDVSaN3P8FpiUfkaKqm1S73bvI3HnMVY0UWazyiZhLptRyLgC8i1HdicboUbBD4ND2pxldq2Y438bllw1tBSvtyqaJ4sI18r1aW3wRikaS6Alla0PO7qNeWbJEeiCBFv9JJh2GS0a6dV+UtHApF//j1dBKiKl3hPEasPbV+Rnus3XDjLFyWrTIdwd9lOovCtQiiqjaps8pB0M1/Wc5uMiY1CGTqWv/D4dQoek5Sz/c//cPaMBtvkUJuNXCa8dZr79rIC9T9M9kkgadtDiInq/pmsptX4QOPXuQ0LgPAhi06Bq2VynAxmU1i730RWxnaB8ziaNzbGpd+vLIXd9GvbeX90LknIqg1ynakjv/yFlquc9Q3jfI3f9lYi0t/Yuvmwtl0bAUpQXylxrVlIL2rkLuXkjJsBkn6WoNv3ATnyla4GEuHPqRXv8KxjmrTbADxAfTLZrZyRFFJN2CHX/1Ou0mtoCP5ZPfA4ZmuKlkRcvFNTwlheHzZwy2iVGexQG+qExO/dPqLIPGyrGE1/iLOf7wRa1B+OMjGdffdHwsWUiQp3ohC+OG7dcrAn85B4sRDSqxwwWU3dO34D7Pja1mBWKCG3XjVg7tVa6VIklGkAG3TYJjW4he0rwiqjFdIHQ7KH3GQ11jt2KcWkN6uE6mDmoSjECVqhc7xZKDmpg4lj1ekWr7+8b2jIgN33orjOJTY6ohdv334vW2loeA8WbGkthdd1x7wpaYkgnJt5gtTvHmyG7oIqhHbsbd7QGhskNqMSON28uKI6E0A5COj9ZUAiCANx13VoGeLflOdIkjxZ+TYehW7wkh+yJbUmWwaZWlCxunJoeATJPC63YJRonFAk1GXTKh1HO5sTBqGbyWyJoZvpuVKITqmPY+CimcmctRZPQ1TjV3swCF2eN104Znh3T/zIaZ63XmBKfadaP4bvva6BxSz5M/ZNrOdh2YvIf6KrNlbxIGDAm3liKMGw4A2//puMZg2HIgU2fsp+966Gn9fTlh2e4skPaqmIKB2NM45d+glxGeK2Nihhjr69sN1BuMl2l+Kg9HSfZ+GUrQ4BmzbmKZdUvNYoTsufCSL0P0QKbYrXJYjiHGjM1voe8jyRBwDzEbL9KK/XhLmaN6pa3dZnK4gYoqSJTmfAPlXszO6ji537zmmSinULVHwsu+T+rLI0cRManttj/ewcTLa6Y5plFNM4ZrVaPdxjO1aGDofGPIoSTx7ENCL85qC/U0L73/YjdKC6KJ/WiP8jAVa+y8SCJOvoEZ1/X8eqjBt5xEhUV/t4cEBptq9HU5ZqCTdka3TiT/sQBAxAlMCF6hKFh68C8LT8nARIoDFedmUL4iMfnG0z2LFiSRVavdsyo+fSg1UiYYbZQx+cJXNUuUYnCBBcqYZQYJNW5tmnG3nWBoNSwGKR+9tweIrkUm1gKG7Qp+TVQbfg116gjQut+CUBJOe5Q8sLSlMiSAW2lrd3bA3b7taSbeHB+qaM/0xh02VhXA+U9eaFgfAvHstwSg+umzjFpyHPqoUBKBsx0kvP3jSRiVyZD0kmpOzNfQzdEsKTjJT142SP7sagSYcHnLmR77VLTZMVltZCAziBytOTpMdEmuT0MoH4NPoSZ8ISaqdlSgwh+DnyVfbaRZPDLlx8zw7I2UNDEjhSoL4mCbb1IgPGk+LIK8bQdKz9fbXiXKr01YuWUFARnZZJiuODEtzPZC6IDERVSY1eerqZ5NG1KWBBcUZOTydQNx1sbUzaXqYO+DcoAdWJeFyB0s92ToqYkSpKZYRUeuGTh8NLSjEuIwjvONPn2ltKJKgJ1ddmXHjhIFnuwLWmUBQbsQRorMHs8HHbCvogZOZytEPaHeonJ9rUATJWRQ5BGocS8fO5qNmcRFVdPvKR1M1OJ4dkQDYbQpBGgUp4hCDaxT8cNjS2qmFij8uzebOIw011IN3E9VO/JzBA9MWzeXOOBEVZJoKQPQVOremJWxvh9wNikdJrI7p2YiTzps9RYQ67eSfHUrTw47WuCMoOcLJO3vi6qehCC8SpSSbTs4JLc8pYYlZGiC6ExdDt3+N7Tvw+A4VagTp9YZf/SDryBMqFVI3Nbl3Vfiku1IEeTUET79zwAO3I4AjSk/CcyZlOIZhoSKNKwg2ptGegwddK+9kkYonjnqGVXo93XJi4I7WGbLPoExI1r2Xg76enKAmcoTMyzHWvDHOPMN2WhQqO2znwgEZQU1n1tXpoGxI5NidBdDhr9V2bZGhTREphwFdDI0V8CK9H0GsKOVS08aX+2n36zr+cqVCXJBqW7Ts2ZcAzApSkrY7kT1b6MWGbJJrrmyIIxnUz/2q25cTPy50+YQebNktUjckmgxJHPlln2jp7jAeUrWfqNg1xvg5IVLG14WXxKMocelODmlx9piq0z2VIkcpEXDtMJ340u118saKUijHZLtrD0/LEAmi0kGObmo8ES9OhX5OscFxcmr7hbTueWfwSX+63xqkcAUpmKg/7WoIFr2LBRrXvhIk3kd7uhQeB2Fu4OQ55ip+3GsqYhSZSNWW2B5sYEk0tmCJaZRTvP2lm62xct4ENws6rJgkpILXsCVv4cPOdJEjYFtqrd793DIIAy1yueRBWuvNELvIwxZjf7LbR0QpYIncnWrrPyy40CIxxwZ5tufIy3OitiT7mym+ShLHmqJlGtnd7Gc7AH58f+XwSqdMcLNq5bpLgRWUpEzPIfr2sJSHdNuFAqU+ahEt2kSj31O28VKCShgkG4OJn/sxG1KakW26LX7QRy6AFYUEfI5ymHd47lpp9UaLy/YePqnb9Tv23U+rKbFCCPD8CKLTRpvYcAP4oa3yAycRK2iom4/9y9374+xW78K4vHrk7sQO+na0HLfrMVoqGVakXRvgZKlEeykVOwju3YP3rPpmy0ms/IaP0XXz/WXnHz8XajA/B/hH29i97GGNtX4Ccv6/d29s9pxQsVM/rZ+A3JTSR+d9n45et5FzStHuMMAPu6T05o0rCPpGgA+ofvsapImktN6RdXVlbTy861t2KyROBhW0biPHksyuPNmB1VhhAsq+9Wkr7Y9pVZXF11HyHxsl9Y6Oyz+4pzkePzXz6h0dVwQlZ1stP1aA9J6OHPjpmsqfeuL1xo6cJXiQN/X5njdfbmWLlb0IcnpEO5KFDjVegcGV5jxcabDkNJxW12LlLTyjvVbHD1a8896NvKDQsZyTc2B33ls0PXPsi6Ftp+qD3rpKMfrJ26kSBwddF/hkc+hWlPpdubKjAYB4DARjZTICmvs23PTkm43rVndLSfwVftu0ze3qj+J1WyWBXz3Ya2PQqz9yJOGJ4F1oOTpejdstIFfiGF3XoD62O3RZPtBEkhcWTtJgZ3q7++MCMHS4P8RRkhQQ3bNNKR9da8LtYpBrffJj38PlOF36+wcn0yvNG4l7eDeW9tfaUu8Eyez9m/l4Hxs1PUSK26Ug9xYC36pqbEP+yWlq3C4JucbC0J1VPqDFRoY35RlfTDBIuLSb6t1e8X80pujVIUA+l300XFlpHti4HZLQ20SAmKVi1JoDWrLQMp4djaYXjNwshDSV0Ju3MOcVrSsiesfIZTEZGvXfHSh22mmn943A3W7tawyEaE/WGXcLNTX3eRSnbazORctfnqMDvYEEKAuFwfY43nkz9E+grneQXColVienG9DbtW5UXPgGug+DuceT7d6U17VGS5ygd5DckxMap9/ONzirKujlI/cuVjnC3r2PZfSH7R16+chlJYSp84kThjh2jb7Rj7KkFI/SC0aw72BfED56DQlc6VW59IXd6xCdJ73aNPLpxSS3/Qo9l9/B6LAjXq8mgeAlqjFZQPTyTq5TcDdquMCYSyuLfwqzk8l3mazeTHIJyWVAIXcd6NseV72W5Fr+GNvNG4BddPWHU6MUg5dbFQjeFfFjek7vJbn8GpVBPccEDVnsWrn1epLLicjO2+gmycE6A9SbSS53DWYsbnafxnp+9GYSCCGl5xim6UFba8+od5RcZuGK+oXw64zfNXDVi0ruNyswILhXAvbEtHWfj95Ucq28D/F9cnqfIz+/s586UVENtRyuQul9YsujRJtdB3p/yfV6AR5The/7aPX6ErgJ28bJp1mlf+2z9faS692QngG98eM6CuWKaQKFdsVgd8XHYdacK6K5QNZzFq+bnljcrRlM1gzU6wfXbf7vyPSNBimQuf4GZ7eELH2Y3lVy+UAW9q3y8BMYC11fIIxrLcDFZ7k8lejnhUaP/j0AZNiwlCuKCYCN7Qeagr3dwquf1433wSSH9XCt/EQe6kMPjeKkWg6GQGr4oT9ccpmG6D0mlzNKwXWshf/qqhXRZMzt3sX3ERLbsaA6RmkDSFPAb+U0CIuj+xAsc41HOuzj+8WO3YeiGC+gKAzXZQQ46pDPFcR4X/CCT6f8wL//AQ==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [day = nullable text, spend_cents = nullable text, leads = nullable text, mqls = nullable text, calls_booked = nullable text, closed_won_deals = nullable text, booked_cents = nullable text, gross_collected_cents = nullable text, refunds_cents = nullable text, net_cash_cents = nullable text]),
				  #"Changed column type" = Table.TransformColumnTypes(Source, {{"day", type date}, {"spend_cents", Int64.Type}, {"leads", Int64.Type}, {"mqls", Int64.Type}, {"calls_booked", Int64.Type}, {"closed_won_deals", Int64.Type}, {"booked_cents", Int64.Type}, {"gross_collected_cents", Int64.Type}, {"refunds_cents", Int64.Type}, {"net_cash_cents", Int64.Type}})
				in
				  #"Changed column type"
