"""Render docs/case-study.md from the live analytics so every number in it is checked.

``python -m growthops.case_study`` rewrites the document; ``tests/test_case_study.py``
fails if the committed copy drifts from what the code computes.
"""

from __future__ import annotations

import argparse
import sqlite3
from datetime import timedelta
from pathlib import Path

from growthops.brief import findings
from growthops.campaign_links import audit_short_links
from growthops.diagnostics import detect, incident_recall
from growthops.email_analytics import deliverability, email_performance
from growthops.experiments import analyze as experiment_analysis
from growthops.hubspot import audit as hubspot_audit
from growthops.migration import audit as migration_audit
from growthops.performance import paid_efficiency
from growthops.reconciliation import (
    crm_bridge,
    four_numbers,
    platform_bridge,
    platform_comparison,
)
from growthops.report import TARGETS, executive_brief
from growthops.scenario import AS_OF, ENROLLMENT_DEADLINE, PROMO_DATES, START
from growthops.workflow import health as workflow_health

OUTPUT = Path(__file__).resolve().parent.parent / "docs" / "case-study.md"


def _usd(cents: float) -> str:
    return f"{'−' if cents < 0 else ''}${abs(cents) / 100:,.0f}"


def _bridge_table(steps: list[dict]) -> str:
    lines = ["| Step | USD |", "|---|---:|"]
    for step in steps:
        label = f"**{step['label']}**" if step["kind"] == "total" else step["label"]
        lines.append(f"| {label} | {_usd(step['cents'])} |")
    return "\n".join(lines)


def render(connection: sqlite3.Connection) -> str:
    summary = executive_brief(connection)
    kpis, quality = summary["metrics"], summary["measurement_health"]
    truth = four_numbers(connection)
    platforms = {row["platform"]: row for row in platform_comparison(connection)}
    episodes = detect(connection)
    recall = incident_recall(connection, episodes)
    quality_episode = next(e for e in episodes if e["episode_id"] == next(
        r["episode_id"] for r in recall if r["incident_id"] == "inc_meta_broad_quality"))
    utm_episode = next(e for e in episodes if e["episode_id"] == next(
        r["episode_id"] for r in recall if r["incident_id"] == "inc_webinar_utm_break"))
    experiment = experiment_analysis(connection, "cta_growth_plan")
    a, b = experiment["variants"]
    comparison = experiment["comparison"]
    ops = workflow_health(connection)
    top = findings(connection)[0]
    migration = migration_audit(connection)
    meta = platforms["meta"]
    email_check = deliverability(connection)
    new_domain = email_check["flagged_domains"][0]
    email_now = next(r for r in email_check["recent_by_domain"] if r["sending_domain"] == new_domain)
    email_base = email_check["baseline_by_domain"][0]
    promos = [r for r in email_performance(connection, "promo")]
    links = audit_short_links(connection)
    broken_links = "; ".join(f"`{link['link_id']}` ({link['issues'][0]})" for link in links["links"] if link["issues"])
    crm = hubspot_audit(connection)
    launch_start, launch_days = PROMO_DATES[0], (ENROLLMENT_DEADLINE - PROMO_DATES[0]).days + 1

    def window_sum(start, days):
        return dict(connection.execute(
            """SELECT SUM(closed_won_deals) won, SUM(net_cash_cents) cash, SUM(calls_booked) calls
               FROM mart_growth_daily WHERE day BETWEEN ? AND ?""",
            (start.isoformat(), (start + timedelta(days=days - 1)).isoformat())).fetchone())
    launch = window_sum(launch_start, launch_days)
    before = window_sum(launch_start - timedelta(days=56), 56)
    per_window = {key: before[key] * launch_days / 56 for key in before}
    paid30 = {row["segment"]: row for row in paid_efficiency(connection, AS_OF - timedelta(days=29), AS_OF)}
    health_rows = "\n".join(
        f"| {label} | {quality[key]:.1%} | {TARGETS[key]:.0%} | {'Pass' if quality[key] >= TARGETS[key] else 'Below target'} |"
        for label, key in (("UTM completeness", "utm_completeness"),
                           ("Campaign registry match", "campaign_registry_match"),
                           ("CRM owner coverage", "crm_owner_completeness"),
                           ("Lifecycle integrity (paid journeys)", "lifecycle_integrity"),
                           ("Payment-to-deal match", "deal_payment_reconciliation")))
    recall_rows = "\n".join(
        f"| {r['description']} | {r['expected']} | {'yes' if r['root_cause_correct'] else 'no'} | {r['days_to_detect']} |"
        for r in recall)
    return f"""# ScaleLab acquisition-to-cash case study

> Generated by `python -m growthops.case_study` from the synthetic scenario; a test fails if any number
> here drifts from the code. ScaleLab is fictional and every record is generated. This is an interview
> demonstration, not a claim of real business impact.

## The situation

ScaleLab is a creator-led B2B education company: free YouTube content and a newsletter feed a lead
magnet and webinars, a sales team closes a Founder Accelerator and Executive Coaching (paid in full or in
instalments), and buyers can add an annual Private Founder Community subscription. The scenario runs from
{START:%d %B %Y} to {AS_OF:%d %B %Y}: {kpis['leads']:,} CRM contacts ({kpis['unique_people']:,} unique people),
{kpis['mqls']:,} MQLs, {kpis['customers']:,} paying customers, {_usd(kpis['spend_cents'])} of paid media and
{_usd(kpis['net_collected_cents'])} of net collected cash.

Six months ago the company migrated from a legacy CRM. Since then leadership has stopped trusting its numbers.

## 1. Which revenue number is right?

| System | What it reports |
|---|---:|
| Meta Ads | {_usd(truth['platform_reported_cents']['meta'])} |
| Google Ads | {_usd(truth['platform_reported_cents']['google'])} |
| LinkedIn Ads | {_usd(truth['platform_reported_cents']['linkedin'])} |
| CRM closed-won deals | {_usd(truth['crm_booked_cents'])} |
| Payment processor, net of refunds | **{_usd(truth['net_collected_cents'])}** |

**Decision: net collected cash is the revenue number.** Platform figures are self-attributed claims and CRM
figures are bookings. Two exact bridges explain every dollar between them; each step is computed
independently and the residual is zero.

**Ad platforms → warehouse paid-media cash.** The platforms together claim more than the business collected
in total. Meta reports {meta['platform_roas']}× ROAS; measured on net cash with lead-creation attribution it
is {meta['warehouse_roas']}×.

{_bridge_table(platform_bridge(connection)['steps'])}

**CRM bookings → cash.**

{_bridge_table(crm_bridge(connection)['steps'])}

## 2. What changed, and why?

The monitor compares each rolling 7-day window with the 56 days before it and splits every material change
across segments with an exact shift-share decomposition. The scenario contains planted incidents, so the
detector can be scored against ground truth:

| Planted incident | Expected signal | Correct root cause | Days to detect |
|---|---|---|---:|
{recall_rows}

- **Lead quality.** {quality_episode['label']} fell from {quality_episode['baseline_text']} to
  {quality_episode['current_text']}. `{quality_episode['top_drivers'][0]['segment']}`, a broad-audience Meta
  campaign launched in August, explains {quality_episode['top_drivers'][0]['share_of_change']:.0%} of the drop.
  The same campaign added lead volume and spend, so the brief reports one story rather than three alerts:
  judge it on cost per MQL, not on leads.
- **Tracking.** UTM completeness fell from {utm_episode['baseline_text']} to {utm_episode['current_text']};
  `{utm_episode['top_drivers'][0]['segment']}` explains {utm_episode['top_drivers'][0]['share_of_change']:.0%}.
  A landing-page release stopped passing UTM parameters, leaving {_usd(quality['unassigned_net_cash_cents'])}
  of net cash that cannot be credited to any campaign.

## 3. Operations: did every buyer get what they paid for?

The last 30 days of payments flow through the lifecycle engine as signed, at-least-once webhooks: record the
payment, update the CRM, grant community access, send onboarding. Each step is idempotent and traced; failures
retry after 5, 10, 20 and 40 minutes and then park in a dead-letter queue.

{ops['events']} payment events were processed and {ops['duplicate_deliveries_absorbed']} duplicate deliveries
were absorbed without a second side effect. On the enrollment-deadline launch day the community-access
provider returned HTTP 503 for six hours. The morning brief's top item:

> **{top['finding']}** {top['evidence']}

Replaying a dead-lettered event is a role-gated API action; the lookup endpoint diagnoses any customer as
"paid but no access" until it is resolved.

## 4. Experiment: more leads is not more money

A "Get my growth plan" CTA was tested against "Book a strategy call", randomized by visitor (sample-ratio
check p = {comparison['sample_ratio_p_value']}).

| Variant | Visitors | Lead rate | MQL per lead | Buyers | Net cash per visitor |
|---|---:|---:|---:|---:|---:|
| {a['label']} | {a['visitors']:,} | {a['lead_rate']:.2%} | {a['mql_per_lead']:.1%} | {a['customers']} | ${a['net_cash_per_visitor_cents'] / 100:.2f} |
| {b['label']} | {b['visitors']:,} | {b['lead_rate']:.2%} | {b['mql_per_lead']:.1%} | {b['customers']} | ${b['net_cash_per_visitor_cents'] / 100:.2f} |

The lead-rate lift is large and significant (p = {comparison['lead_rate_p_value']}); the cash-per-visitor
difference has a bootstrap 95% interval of ${comparison['cash_per_visitor_bootstrap_95_ci_cents'][0] / 100:.2f}
to ${comparison['cash_per_visitor_bootstrap_95_ci_cents'][1] / 100:.2f}. **{comparison['decision']}**

## 5. Email, links and the enrollment deadline

**Launch readout.** In the {launch_days} days from the first promo ({launch_start:%d %B}) to the enrollment deadline
({ENROLLMENT_DEADLINE:%d %B}), {launch['won']} deals closed and {_usd(launch['cash'])} of net cash was collected, against
{per_window['won']:.0f} deals and {_usd(per_window['cash'])} in an average {launch_days}-day stretch of the prior eight weeks.
The deadline worked, but three things went wrong around it, and each shows up in its own check:

- **Email deliverability.** Bulk sends moved to `{new_domain}` on {email_check['affected_emails'][0]['sent_date']}.
  Across its {email_now['emails']} sends the bounce rate was {email_now['bounce_rate']:.1%} and the complaint rate
  {email_now['complaint_rate']:.2%} (limits 2% and 0.1%); the human open rate fell to {email_now['human_open_rate']:.1%}
  from {email_base['human_open_rate']:.1%}. All {len(promos)} deadline promos went out on the new domain. Reported open
  rates hide part of this, because privacy-proxy machine opens are counted as opens.
- **Links.** {links['links_with_issues']} of {len(links['links'])} short links fail the registry check: {broken_links}.
  They carried {links['share_of_recent_clicks_broken']:.0%} of short-link clicks in the last {links['recent_days']} days.
- **Access.** The six-hour provider outage on launch day is the dead-letter finding in section 3.

**Paid efficiency, last 30 days** (activity basis): {_usd(paid30['meta_prospecting_founder']['cost_per_booked_call_cents'])}
per booked call on `meta_prospecting_founder` against
{_usd(paid30['meta_broad_v17']['cost_per_booked_call_cents'])} on `meta_broad_v17`; paid media overall
{_usd(paid30['Total paid']['cost_per_lead_cents'])} per lead and {_usd(paid30['Total paid']['cost_per_mql_cents'])} per MQL.

## 6. Can we trust the data?

| Check | Actual | Target | Status |
|---|---:|---:|---|
{health_rows}

The migration audit matched {migration['migrated_contacts']:,} of {migration['legacy_contacts']:,} legacy
contacts ({migration['missing_contacts']} missing) and found {migration['duplicate_crm_rows']} duplicate CRM rows.
The safe-repair command restores blank owners and placeholder sources from unambiguous legacy matches and logs
every change; duplicates, missing contacts and stage regressions are left for a person.

Mapped onto HubSpot's standard properties (`lifecyclestage`, `dealstage`, `hubspot_owner_id`), an import would merge
{crm['rows_merged_on_email']} rows on email; {crm['paying_contacts_not_customer']} paying contacts and
{crm['closed_won_contacts_not_customer']} closed-won contacts are not at the customer stage, and
{crm['stale_leads_non_marketing_candidates']:,} leads untouched for a year are candidates to set as non-marketing
contacts, which lowers the HubSpot marketing-contact tier.

## Limits

The data is generated, the provider adapters are simulated, and attribution is descriptive (lead creation),
not incremental. A production version needs real source contracts, authentication and credential rotation,
privacy review, provider sandbox tests, scheduled ingestion with freshness monitoring, and incrementality
testing (geo holdouts or conversion-lift studies) before budget moves on attribution alone.
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--database", default="data/growthops-sample.db")
    args = parser.parse_args()
    from growthops.db import connect

    connection = connect(args.database)
    try:
        OUTPUT.write_text(render(connection), encoding="utf-8")
    finally:
        connection.close()
    print(OUTPUT)


if __name__ == "__main__":
    main()
